using System.Windows;
using System.Windows.Controls;
using System.Data;
using WPF_LoginForm.ViewModels;

namespace WPF_LoginForm.Views
{
    public partial class DatarepView : UserControl
    {
        public DatarepView()
        {
            InitializeComponent();
        }

        // --- 1. FORCE COLUMNS TO BE EDITABLE ---
        // AutoGenerated columns often default to ReadOnly. We must force them open.
        private void DataDisplayGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyName == "ID")
            {
                // 1. Bind Visibility to IsIdVisible
                var visBinding = new System.Windows.Data.Binding("IsIdVisible")
                {
                    Source = this.DataContext,
                    Converter = (System.Windows.Data.IValueConverter)this.Resources["BooleanToVisibilityConverter"]
                };
                System.Windows.Data.BindingOperations.SetBinding(e.Column, DataGridColumn.VisibilityProperty, visBinding);

                // 2. Bind IsReadOnly to !IsIdEditable
                var readOnlyBinding = new System.Windows.Data.Binding("IsIdEditable")
                {
                    Source = this.DataContext,
                    Converter = (System.Windows.Data.IValueConverter)this.Resources["BooleanInverter"]
                };
                System.Windows.Data.BindingOperations.SetBinding(e.Column, DataGridColumn.IsReadOnlyProperty, readOnlyBinding);
            }
            else
            {
                e.Column.IsReadOnly = false;
            }

            if (e.PropertyType == typeof(System.DateTime))
            {
                var column = e.Column as DataGridTextColumn;
                if (column != null && column.Binding is System.Windows.Data.Binding originalBinding)
                {
                    // Create a MultiBinding to handle dynamic format change based on IsTimeCorrectionEnabled
                    var multiBinding = new System.Windows.Data.MultiBinding
                    {
                        Converter = (System.Windows.Data.IMultiValueConverter)this.Resources["DateTimeCorrectionConverter"],
                        Mode = originalBinding.Mode,
                        UpdateSourceTrigger = originalBinding.UpdateSourceTrigger
                    };

                    // 1. The actual value from the row
                    multiBinding.Bindings.Add(new System.Windows.Data.Binding(e.PropertyName));

                    // 2. The toggle state from the ViewModel
                    multiBinding.Bindings.Add(new System.Windows.Data.Binding("IsTimeCorrectionEnabled")
                    {
                        Source = this.DataContext
                    });

                    column.Binding = multiBinding;
                }
            }
        }

        // --- 2. RESTRICT EDITING TO SELECTED ROWS ---
        // This is the gatekeeper. Even if the column is editable, this event checks the Row.
        private void DataDisplayGrid_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            // Get ViewModel
            var viewModel = this.DataContext as DatarepViewModel;
            if (viewModel == null) return;

            // Get the row being edited
            var rowView = e.Row.Item as DataRowView;

            // CHECK: Is this row in our "EditableRows" list?
            // If the list is empty OR the row isn't in it, CANCEL the edit.
            if (viewModel.EditableRows == null || !viewModel.EditableRows.Contains(rowView))
            {
                e.Cancel = true; // Block the edit
            }
        }

        // Logic for Select All button
        private void SelectAllButton_Click(object sender, RoutedEventArgs e)
        {
            DataDisplayGrid.SelectAll();
        }

        // Sorting logic (Default is fine)
        private void DataDisplayGrid_Sorting(object sender, DataGridSortingEventArgs e)
        {
            // Leave empty to use default DataGrid sorting
        }
    }
}