using System.Windows;
using System.Windows.Controls;
using System.Data;
using WPF_LoginForm.ViewModels;

namespace WPF_LoginForm.Views
{
    public partial class DatarepView : UserControl
    {
        public DatarepView()
        {
            InitializeComponent();
        }

        // --- 1. FORCE COLUMNS TO BE EDITABLE ---
        // AutoGenerated columns often default to ReadOnly. We must force them open.
        private void DataDisplayGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            // Keep ID column locked (optional, depends on your needs)
            if (e.PropertyName == "ID")
            {
                e.Column.IsReadOnly = true;
            }
            else
            {
                // Force all other columns to be editable
                e.Column.IsReadOnly = false;
            }

            // Optional: formatting for dates
            if (e.PropertyType == typeof(System.DateTime))
            {
                (e.Column as DataGridTextColumn).Binding.StringFormat = "dd/MM/yyyy HH:mm";
            }
        }

        // --- 2. RESTRICT EDITING TO SELECTED ROWS ---
        // This is the gatekeeper. Even if the column is editable, this event checks the Row.
        private void DataDisplayGrid_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            // Get ViewModel
            var viewModel = this.DataContext as DatarepViewModel;
            if (viewModel == null) return;

            // Get the row being edited
            var rowView = e.Row.Item as DataRowView;

            // CHECK: Is this row in our "EditableRows" list?
            // If the list is empty OR the row isn't in it, CANCEL the edit.
            if (viewModel.EditableRows == null || !viewModel.EditableRows.Contains(rowView))
            {
                e.Cancel = true; // Block the edit
            }
        }

        // Logic for Select All button
        private void SelectAllButton_Click(object sender, RoutedEventArgs e)
        {
            DataDisplayGrid.SelectAll();
        }

        // Sorting logic (Default is fine)
        private void DataDisplayGrid_Sorting(object sender, DataGridSortingEventArgs e)
        {
            // Leave empty to use default DataGrid sorting
        }
    }
}