using System.Windows;
using System.Windows.Controls;
using System.Data;
using WPF_LoginForm.ViewModels;

namespace WPF_LoginForm.Views
{
    public partial class DatarepView : UserControl
    {
        public DatarepView()
        {
            InitializeComponent();
        }

        // --- 1. FORCE COLUMNS TO BE EDITABLE ---
        // AutoGenerated columns often default to ReadOnly. We must force them open.
        private void DataDisplayGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            // --- OVERRIDE DEFAULT EDITING STYLE ---
            if (e.Column is DataGridTextColumn defaultTxtCol)
            {
                var editingStyle = DataDisplayGrid.Resources["DataGridEditingTextBoxStyle"] as System.Windows.Style;
                if (editingStyle != null) defaultTxtCol.EditingElementStyle = editingStyle;
            }

            // --- ID COLUMN LOGIC ---
            if (e.PropertyName == "ID")
            {
                var visBinding = new System.Windows.Data.Binding("IsIdVisible")
                {
                    Source = this.DataContext,
                    Converter = (System.Windows.Data.IValueConverter)this.Resources["BooleanToVisibilityConverter"]
                };
                System.Windows.Data.BindingOperations.SetBinding(e.Column, DataGridColumn.VisibilityProperty, visBinding);

                var readOnlyBinding = new System.Windows.Data.Binding("IsIdEditable")
                {
                    Source = this.DataContext,
                    Converter = (System.Windows.Data.IValueConverter)this.Resources["BooleanInverter"]
                };
                System.Windows.Data.BindingOperations.SetBinding(e.Column, DataGridColumn.IsReadOnlyProperty, readOnlyBinding);
            }
            else
            {
                e.Column.IsReadOnly = false;
            }

            // --- DATETIME LOGIC ---
            if (e.PropertyType == typeof(System.DateTime))
            {
                if (e.Column is DataGridTextColumn column && column.Binding is System.Windows.Data.Binding originalBinding)
                {
                    var multiBinding = new System.Windows.Data.MultiBinding
                    {
                        Converter = (System.Windows.Data.IMultiValueConverter)this.Resources["DateTimeCorrectionConverter"],
                        Mode = originalBinding.Mode,
                        UpdateSourceTrigger = originalBinding.UpdateSourceTrigger
                    };
                    multiBinding.Bindings.Add(new System.Windows.Data.Binding(e.PropertyName));
                    multiBinding.Bindings.Add(new System.Windows.Data.Binding("IsTimeCorrectionEnabled") { Source = this.DataContext });
                    column.Binding = multiBinding;
                }
            }

            // --- NUMERIC COLUMNS LOGIC ---
            if (e.PropertyType == typeof(int) || e.PropertyType == typeof(long) ||
                e.PropertyType == typeof(double) || e.PropertyType == typeof(float) ||
                e.PropertyType == typeof(decimal) || e.PropertyType == typeof(short))
            {
                if (e.Column is DataGridTextColumn txtCol)
                {
                    var displayStyle = new System.Windows.Style(typeof(System.Windows.Controls.TextBlock), txtCol.ElementStyle);
                    displayStyle.Setters.Add(new System.Windows.Setter(System.Windows.Controls.TextBlock.TextAlignmentProperty, System.Windows.TextAlignment.Right));
                    displayStyle.Setters.Add(new System.Windows.Setter(System.Windows.Controls.TextBlock.MarginProperty, new System.Windows.Thickness(0, 0, 16, 0)));
                    displayStyle.Setters.Add(new System.Windows.Setter(System.Windows.Controls.TextBlock.FontFamilyProperty, new System.Windows.Media.FontFamily("Consolas")));
                    txtCol.ElementStyle = displayStyle;

                    var baseEditStyle = DataDisplayGrid.Resources["DataGridEditingTextBoxStyle"] as System.Windows.Style;
                    if (baseEditStyle != null)
                    {
                        var numEditStyle = new System.Windows.Style(typeof(System.Windows.Controls.TextBox), baseEditStyle);
                        numEditStyle.Setters.Add(new System.Windows.Setter(System.Windows.Controls.TextBox.TextAlignmentProperty, System.Windows.TextAlignment.Right));
                        numEditStyle.Setters.Add(new System.Windows.Setter(System.Windows.Controls.TextBox.FontFamilyProperty, new System.Windows.Media.FontFamily("Consolas")));
                        txtCol.EditingElementStyle = numEditStyle;
                    }

                    if (e.PropertyType == typeof(double) || e.PropertyType == typeof(float) || e.PropertyType == typeof(decimal))
                    {
                        if (txtCol.Binding is System.Windows.Data.Binding b)
                            txtCol.Binding = new System.Windows.Data.Binding(b.Path.Path) { StringFormat = "N2", Mode = b.Mode };
                    }
                }
            }
        }

        // --- 2. RESTRICT EDITING TO SELECTED ROWS ---
        // This is the gatekeeper. Even if the column is editable, this event checks the Row.
        private void DataDisplayGrid_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {
            // Get ViewModel
            var viewModel = this.DataContext as DatarepViewModel;
            if (viewModel == null) return;

            // Get the row being edited
            var rowView = e.Row.Item as DataRowView;

            // CHECK: Is this row in our "EditableRows" list?
            // If the list is empty OR the row isn't in it, CANCEL the edit.
            if (viewModel.EditableRows == null || !viewModel.EditableRows.Contains(rowView))
            {
                e.Cancel = true; // Block the edit
            }
        }

        // Logic for Select All button
        private void SelectAllButton_Click(object sender, RoutedEventArgs e)
        {
            DataDisplayGrid.SelectAll();
        }

        // Sorting logic (Default is fine)
        private void DataDisplayGrid_Sorting(object sender, DataGridSortingEventArgs e)
        {
            // Leave empty to use default DataGrid sorting
        }
    }
}