//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Properties {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LoginForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        public static string AddDataLine {
            get {
                return ResourceManager.GetString("AddDataLine", resourceCulture);
            }
        }
        public static string AddId {
            get {
                return ResourceManager.GetString("AddId", resourceCulture);
            }
        }
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        public static string CreateNewTable {
            get {
                return ResourceManager.GetString("CreateNewTable", resourceCulture);
            }
        }
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        public static string DbProvider {
            get {
                return ResourceManager.GetString("DbProvider", resourceCulture);
            }
        }
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        public static string EditId {
            get {
                return ResourceManager.GetString("EditId", resourceCulture);
            }
        }
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        public static string FilterbyDate {
            get {
                return ResourceManager.GetString("FilterbyDate", resourceCulture);
            }
        }
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        public static string HideId {
            get {
                return ResourceManager.GetString("HideId", resourceCulture);
            }
        }
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        public static string LoadFullHistory {
            get {
                return ResourceManager.GetString("LoadFullHistory", resourceCulture);
            }
        }
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        public static string Msg_AccessDeniedRole {
            get {
                return ResourceManager.GetString("Msg_AccessDeniedRole", resourceCulture);
            }
        }
        public static string Msg_DbInitFailed {
            get {
                return ResourceManager.GetString("Msg_DbInitFailed", resourceCulture);
            }
        }
        public static string Msg_InvalidCredentials {
            get {
                return ResourceManager.GetString("Msg_InvalidCredentials", resourceCulture);
            }
        }
        public static string Msg_NetworkUnreachable {
            get {
                return ResourceManager.GetString("Msg_NetworkUnreachable", resourceCulture);
            }
        }
        public static string Msg_SettingsSavedRestart {
            get {
                return ResourceManager.GetString("Msg_SettingsSavedRestart", resourceCulture);
            }
        }
        public static string Msg_UserAdded {
            get {
                return ResourceManager.GetString("Msg_UserAdded", resourceCulture);
            }
        }
        public static string Msg_UserDeleted {
            get {
                return ResourceManager.GetString("Msg_UserDeleted", resourceCulture);
            }
        }
        public static string Nav_Customers {
            get {
                return ResourceManager.GetString("Nav_Customers", resourceCulture);
            }
        }
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        public static string Nav_Help {
            get {
                return ResourceManager.GetString("Nav_Help", resourceCulture);
            }
        }
        public static string Nav_Logs {
            get {
                return ResourceManager.GetString("Nav_Logs", resourceCulture);
            }
        }
        public static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav_Reports", resourceCulture);
            }
        }
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        public static string QuickSearch {
            get {
                return ResourceManager.GetString("QuickSearch", resourceCulture);
            }
        }
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        public static string RenameColumn {
            get {
                return ResourceManager.GetString("RenameColumn", resourceCulture);
            }
        }
        public static string ReportMode {
            get {
                return ResourceManager.GetString("ReportMode", resourceCulture);
            }
        }
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        public static string Tip_CreateNewTable {
            get {
                return ResourceManager.GetString("Tip_CreateNewTable", resourceCulture);
            }
        }
        public static string Tip_LoadFullHistory {
            get {
                return ResourceManager.GetString("Tip_LoadFullHistory", resourceCulture);
            }
        }
        public static string Tip_RenameColumn {
            get {
                return ResourceManager.GetString("Tip_RenameColumn", resourceCulture);
            }
        }
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        public static string Ana_Title {
            get {
                return ResourceManager.GetString("Ana_Title", resourceCulture);
            }
        }
        public static string Ana_Table {
            get {
                return ResourceManager.GetString("Ana_Table", resourceCulture);
            }
        }
        public static string Ana_Category {
            get {
                return ResourceManager.GetString("Ana_Category", resourceCulture);
            }
        }
        public static string Ana_ExcludeMachine00 {
            get {
                return ResourceManager.GetString("Ana_ExcludeMachine00", resourceCulture);
            }
        }
        public static string Ana_LoadData {
            get {
                return ResourceManager.GetString("Ana_LoadData", resourceCulture);
            }
        }
        public static string Ana_StartDate {
            get {
                return ResourceManager.GetString("Ana_StartDate", resourceCulture);
            }
        }
        public static string Ana_EndDate {
            get {
                return ResourceManager.GetString("Ana_EndDate", resourceCulture);
            }
        }
        public static string Chart_LongestIncident {
            get {
                return ResourceManager.GetString("Chart_LongestIncident", resourceCulture);
            }
        }
        public static string Chart_MachineDist {
            get {
                return ResourceManager.GetString("Chart_MachineDist", resourceCulture);
            }
        }
        public static string Chart_ShiftDist {
            get {
                return ResourceManager.GetString("Chart_ShiftDist", resourceCulture);
            }
        }
        public static string DurationText {
            get {
                return ResourceManager.GetString("DurationText", resourceCulture);
            }
        }
        public static string Drill_Title {
            get {
                return ResourceManager.GetString("Drill_Title", resourceCulture);
            }
        }
        public static string Drill_Count {
            get {
                return ResourceManager.GetString("Drill_Count", resourceCulture);
            }
        }
        public static string Drill_TotalDuration {
            get {
                return ResourceManager.GetString("Drill_TotalDuration", resourceCulture);
            }
        }
        public static string Col_Timeline {
            get {
                return ResourceManager.GetString("Col_Timeline", resourceCulture);
            }
        }
        public static string Col_Duration {
            get {
                return ResourceManager.GetString("Col_Duration", resourceCulture);
            }
        }
        public static string Col_Machine {
            get {
                return ResourceManager.GetString("Col_Machine", resourceCulture);
            }
        }
        public static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        public static string Col_Shift {
            get {
                return ResourceManager.GetString("Col_Shift", resourceCulture);
            }
        }
        public static string Str_Find {
            get {
                return ResourceManager.GetString("Str_Find", resourceCulture);
            }
        }
        public static string Str_Replace {
            get {
                return ResourceManager.GetString("Str_Replace", resourceCulture);
            }
        }
        public static string Str_FindWhat {
            get {
                return ResourceManager.GetString("Str_FindWhat", resourceCulture);
            }
        }
        public static string Str_ReplaceWith {
            get {
                return ResourceManager.GetString("Str_ReplaceWith", resourceCulture);
            }
        }
        public static string Str_MatchCase {
            get {
                return ResourceManager.GetString("Str_MatchCase", resourceCulture);
            }
        }
        public static string Str_CategoryConfig {
            get {
                return ResourceManager.GetString("Str_CategoryConfig", resourceCulture);
            }
        }
        public static string Str_MappingRule {
            get {
                return ResourceManager.GetString("Str_MappingRule", resourceCulture);
            }
        }
        public static string Str_MapTo {
            get {
                return ResourceManager.GetString("Str_MapTo", resourceCulture);
            }
        }
        public static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit_Minutes", resourceCulture);
            }
        }
        public static string Col_Date {
            get {
                return ResourceManager.GetString("Col_Date", resourceCulture);
            }
        }
        public static string Machine_Selected {
            get {
                return ResourceManager.GetString("Machine_Selected", resourceCulture);
            }
        }
        public static string Error_Analysis {
            get {
                return ResourceManager.GetString("Error_Analysis", resourceCulture);
            }
        }
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        public static string Min2clock {
            get {
                return ResourceManager.GetString("Min2clock", resourceCulture);
            }
        }
        public static string Max_but {
            get {
                return ResourceManager.GetString("Max_but", resourceCulture);
            }
        }
        public static string AnalyticsP2_Error {
            get {
                return ResourceManager.GetString("AnalyticsP2_Error", resourceCulture);
            }
        }
        public static string AnalyticsP2_Stop {
            get {
                return ResourceManager.GetString("AnalyticsP2_Stop", resourceCulture);
            }
        }
        public static string AnalyticsP2_PieTitle_1 {
            get {
                return ResourceManager.GetString("AnalyticsP2_PieTitle_1", resourceCulture);
            }
        }
        public static string AnalyticsP2_PieTitle_2 {
            get {
                return ResourceManager.GetString("AnalyticsP2_PieTitle_2", resourceCulture);
            }
        }
        public static string AnalyticsP2_BarTitle {
            get {
                return ResourceManager.GetString("AnalyticsP2_BarTitle", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_1 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_1", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_2 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_2", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_3 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_3", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_7 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_7", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_5 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_5", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_6 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_6", resourceCulture);
            }
        }
        public static string AnalyticsP2_Card_4 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_4", resourceCulture);
            }
        }
        public static string P_date {
            get {
                return ResourceManager.GetString("P_date", resourceCulture);
            }
        }
        public static string P_Shift {
            get {
                return ResourceManager.GetString("P_Shift", resourceCulture);
            }
        }
        public static string P_Running {
            get {
                return ResourceManager.GetString("P_Running", resourceCulture);
            }
        }
        public static string P_Meal_and_breaks {
            get {
                return ResourceManager.GetString("P_Meal_and_breaks", resourceCulture);
            }
        }
        public static string P_Errors_and_Stops {
            get {
                return ResourceManager.GetString("P_Errors_and_Stops", resourceCulture);
            }
        }
        public static string P_Overlapping {
            get {
                return ResourceManager.GetString("P-Overlapping", resourceCulture);
            }
        }
        public static string P_Total_Stop {
            get {
                return ResourceManager.GetString("P_Total_Stop", resourceCulture);
            }
        }
        public static string P_Working_Time {
            get {
                return ResourceManager.GetString("P_Working_Time", resourceCulture);
            }
        }
        public static string Str_MA00_1 {
            get {
                return ResourceManager.GetString("Str_MA00_1", resourceCulture);
            }
        }
        public static string Str_OverlapCascadeStep {
            get {
                return ResourceManager.GetString("Str_OverlapCascadeStep", resourceCulture);
            }
        }
        public static string Str_AdvancedLayoutToggles {
            get {
                return ResourceManager.GetString("Str_AdvancedLayoutToggles", resourceCulture);
            }
        }
        public static string Str_MA00_2 {
            get {
                return ResourceManager.GetString("Str_MA00_2", resourceCulture);
            }
        }
        public static string Str_FootnoteDescription {
            get {
                return ResourceManager.GetString("Str_FootnoteDescription", resourceCulture);
            }
        }
        public static string Tip_OverlapCascade {
            get {
                return ResourceManager.GetString("Tip_OverlapCascade", resourceCulture);
            }
        }
        public static string Str_MA00_4 {
            get {
                return ResourceManager.GetString("Str_MA00_4", resourceCulture);
            }
        }
        public static string Str_OverlapErrorColon {
            get {
                return ResourceManager.GetString("Str_OverlapErrorColon", resourceCulture);
            }
        }
        public static string Str_EditWarning {
            get {
                return ResourceManager.GetString("Str_EditWarning", resourceCulture);
            }
        }
        public static string Str_MinMinutesLabel {
            get {
                return ResourceManager.GetString("Str_MinMinutesLabel", resourceCulture);
            }
        }
        public static string Str_FacilityStoppedColon {
            get {
                return ResourceManager.GetString("Str_FacilityStoppedColon", resourceCulture);
            }
        }
        public static string Str_MA00_3 {
            get {
                return ResourceManager.GetString("Str_MA00_3", resourceCulture);
            }
        }
        public static string Str_LayerExplanation {
            get {
                return ResourceManager.GetString("Str_LayerExplanation", resourceCulture);
            }
        }
        public static string Tip_ResetOverrides {
            get {
                return ResourceManager.GetString("Tip_ResetOverrides", resourceCulture);
            }
        }
        public static string Str_MinMinutesFootnote {
            get {
                return ResourceManager.GetString("Str_MinMinutesFootnote", resourceCulture);
            }
        }
        public static string Str_ForceIntoFootnotes {
            get {
                return ResourceManager.GetString("Str_ForceIntoFootnotes", resourceCulture);
            }
        }
        public static string Str_ShowMajorErrorLabels {
            get {
                return ResourceManager.GetString("Str_ShowMajorErrorLabels", resourceCulture);
            }
        }
        public static string Str_BypassColon {
            get {
                return ResourceManager.GetString("Str_BypassColon", resourceCulture);
            }
        }
        public static string Str_PrimaryErrorColon {
            get {
                return ResourceManager.GetString("Str_PrimaryErrorColon", resourceCulture);
            }
        }
        public static string Str_Analytics {
            get {
                return ResourceManager.GetString("Str_Analytics", resourceCulture);
            }
        }
        public static string Str_DailyTimeline {
            get {
                return ResourceManager.GetString("Str_DailyTimeline", resourceCulture);
            }
        }
        public static string Str_MolaBakimKazanimi {
            get {
                return ResourceManager.GetString("Str_MolaBakimKazanimi", resourceCulture);
            }
        }
        public static string Str_BypassKazanimi {
            get {
                return ResourceManager.GetString("Str_BypassKazanimi", resourceCulture);
            }
        }
        public static string Str_FiiliSure {
            get {
                return ResourceManager.GetString("Str_FiiliSure", resourceCulture);
            }
        }
        public static string Str_YanlisZamanVerisi {
            get {
                return ResourceManager.GetString("Str_YanlisZamanVerisi", resourceCulture);
            }
        }
        public static string Str_BozukVeri {
            get {
                return ResourceManager.GetString("Str_BozukVeri", resourceCulture);
            }
        }
        public static string Str_DayShift {
            get {
                return ResourceManager.GetString("Str_DayShift", resourceCulture);
            }
        }
        public static string Str_NightShift {
            get {
                return ResourceManager.GetString("Str_NightShift", resourceCulture);
            }
        }
        public static string Str_Zoom {
            get {
                return ResourceManager.GetString("Str_Zoom", resourceCulture);
            }
        }
        public static string Str_RefData {
            get {
                return ResourceManager.GetString("Str_RefData", resourceCulture);
            }
        }
        public static string Str_Items {
            get {
                return ResourceManager.GetString("Str_Items", resourceCulture);
            }
        }
        public static string Str_StartTime {
            get {
                return ResourceManager.GetString("Str_StartTime", resourceCulture);
            }
        }
        public static string Str_EndTime {
            get {
                return ResourceManager.GetString("Str_EndTime", resourceCulture);
            }
        }
        public static string Str_DurationMin {
            get {
                return ResourceManager.GetString("Str_DurationMin", resourceCulture);
            }
        }
        public static string Str_SpecifyEndTime {
            get {
                return ResourceManager.GetString("Str_SpecifyEndTime", resourceCulture);
            }
        }
        public static string Str_MachineCode {
            get {
                return ResourceManager.GetString("Str_MachineCode", resourceCulture);
            }
        }
        public static string Str_Description {
            get {
                return ResourceManager.GetString("Str_Description", resourceCulture);
            }
        }
        public static string Str_FlagAsBypass {
            get {
                return ResourceManager.GetString("Str_FlagAsBypass", resourceCulture);
            }
        }
        public static string Str_SaveAsFavorite {
            get {
                return ResourceManager.GetString("Str_SaveAsFavorite", resourceCulture);
            }
        }
        public static string Str_ApplyToTimeline {
            get {
                return ResourceManager.GetString("Str_ApplyToTimeline", resourceCulture);
            }
        }
        public static string Str_EventDetails {
            get {
                return ResourceManager.GetString("Str_EventDetails", resourceCulture);
            }
        }
        public static string Str_FavsHint {
            get {
                return ResourceManager.GetString("Str_FavsHint", resourceCulture);
            }
        }
        public static string Str_FavsWithIcon {
            get {
                return ResourceManager.GetString("Str_FavsWithIcon", resourceCulture);
            }
        }
        public static string Str_AddNewWithIcon {
            get {
                return ResourceManager.GetString("Str_AddNewWithIcon", resourceCulture);
            }
        }
        public static string Str_SaveWithIcon {
            get {
                return ResourceManager.GetString("Str_SaveWithIcon", resourceCulture);
            }
        }
        public static string Str_Edit {
            get {
                return ResourceManager.GetString("Str_Edit", resourceCulture);
            }
        }
        public static string Tip_SelectDate {
            get {
                return ResourceManager.GetString("Tip_SelectDate", resourceCulture);
            }
        }
        public static string Tip_UndoChanges {
            get {
                return ResourceManager.GetString("Tip_UndoChanges", resourceCulture);
            }
        }
        public static string Tip_RefreshDB {
            get {
                return ResourceManager.GetString("Tip_RefreshDB", resourceCulture);
            }
        }
        public static string Tip_RemoveFavorite {
            get {
                return ResourceManager.GetString("Tip_RemoveFavorite", resourceCulture);
            }
        }
        public static string Tip_ConfigMachineCodes {
            get {
                return ResourceManager.GetString("Tip_ConfigMachineCodes", resourceCulture);
            }
        }
        public static string Str_HourlyTimeCorrection {
            get {
                return ResourceManager.GetString("Str_HourlyTimeCorrection", resourceCulture);
            }
        }
        public static string Tip_HourlyTimeCorrection {
            get {
                return ResourceManager.GetString("Tip_HourlyTimeCorrection", resourceCulture);
            }
        }
        public static string Str_AdvancedImport {
            get {
                return ResourceManager.GetString("Str_AdvancedImport", resourceCulture);
            }
        }
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        public static string Tab_Configuration {
            get {
                return ResourceManager.GetString("Tab_Configuration", resourceCulture);
            }
        }
        public static string GeneralConfigFile {
            get {
                return ResourceManager.GetString("GeneralConfigFile", resourceCulture);
            }
        }
        public static string GeneralConfigDesc {
            get {
                return ResourceManager.GetString("GeneralConfigDesc", resourceCulture);
            }
        }
        public static string CurrentPath {
            get {
                return ResourceManager.GetString("CurrentPath", resourceCulture);
            }
        }
        public static string Btn_Change {
            get {
                return ResourceManager.GetString("Btn_Change", resourceCulture);
            }
        }
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        public static string DbConnectionConfig {
            get {
                return ResourceManager.GetString("DbConnectionConfig", resourceCulture);
            }
        }
        public static string ServerAddressHost {
            get {
                return ResourceManager.GetString("ServerAddressHost", resourceCulture);
            }
        }
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        public static string ServerComputerName {
            get {
                return ResourceManager.GetString("ServerComputerName", resourceCulture);
            }
        }
        public static string UseWindowsAuth {
            get {
                return ResourceManager.GetString("UseWindowsAuth", resourceCulture);
            }
        }
        public static string DbUsername {
            get {
                return ResourceManager.GetString("DbUsername", resourceCulture);
            }
        }
        public static string DbPassword {
            get {
                return ResourceManager.GetString("DbPassword", resourceCulture);
            }
        }
        public static string NetworkRemoteSettings {
            get {
                return ResourceManager.GetString("NetworkRemoteSettings", resourceCulture);
            }
        }
        public static string ConnectionTimeoutSec {
            get {
                return ResourceManager.GetString("ConnectionTimeoutSec", resourceCulture);
            }
        }
        public static string TrustServerCertificate {
            get {
                return ResourceManager.GetString("TrustServerCertificate", resourceCulture);
            }
        }
        public static string AutomationDashboardFolder {
            get {
                return ResourceManager.GetString("AutomationDashboardFolder", resourceCulture);
            }
        }
        public static string EnableDashboardFolderScan {
            get {
                return ResourceManager.GetString("EnableDashboardFolderScan", resourceCulture);
            }
        }
        public static string FolderRelativeApp {
            get {
                return ResourceManager.GetString("FolderRelativeApp", resourceCulture);
            }
        }
        public static string FolderSpecificPath {
            get {
                return ResourceManager.GetString("FolderSpecificPath", resourceCulture);
            }
        }
        public static string FolderPath {
            get {
                return ResourceManager.GetString("FolderPath", resourceCulture);
            }
        }
        public static string DefaultDashboardFile {
            get {
                return ResourceManager.GetString("DefaultDashboardFile", resourceCulture);
            }
        }
        public static string OfflineModeConfig {
            get {
                return ResourceManager.GetString("OfflineModeConfig", resourceCulture);
            }
        }
        public static string OfflineDataFolder {
            get {
                return ResourceManager.GetString("OfflineDataFolder", resourceCulture);
            }
        }
        public static string CreateOfflineDataImage {
            get {
                return ResourceManager.GetString("CreateOfflineDataImage", resourceCulture);
            }
        }
        public static string OfflineDataImageDesc {
            get {
                return ResourceManager.GetString("OfflineDataImageDesc", resourceCulture);
            }
        }
        public static string LoadAvailableTables {
            get {
                return ResourceManager.GetString("LoadAvailableTables", resourceCulture);
            }
        }
        public static string CreateOfflineBackup {
            get {
                return ResourceManager.GetString("CreateOfflineBackup", resourceCulture);
            }
        }
        public static string PerformanceOptimization {
            get {
                return ResourceManager.GetString("PerformanceOptimization", resourceCulture);
            }
        }
        public static string DefaultRowLimit {
            get {
                return ResourceManager.GetString("DefaultRowLimit", resourceCulture);
            }
        }
        public static string ShowDateFilterDashboard {
            get {
                return ResourceManager.GetString("ShowDateFilterDashboard", resourceCulture);
            }
        }
        public static string DateSliderTickSize {
            get {
                return ResourceManager.GetString("DateSliderTickSize", resourceCulture);
            }
        }
        public static string Tab_UserManagement {
            get {
                return ResourceManager.GetString("Tab_UserManagement", resourceCulture);
            }
        }
        public static string Btn_RefreshList {
            get {
                return ResourceManager.GetString("Btn_RefreshList", resourceCulture);
            }
        }
        public static string Grid_ID {
            get {
                return ResourceManager.GetString("Grid_ID", resourceCulture);
            }
        }
        public static string Grid_Username {
            get {
                return ResourceManager.GetString("Grid_Username", resourceCulture);
            }
        }
        public static string Grid_Role {
            get {
                return ResourceManager.GetString("Grid_Role", resourceCulture);
            }
        }
        public static string Grid_FirstName {
            get {
                return ResourceManager.GetString("Grid_FirstName", resourceCulture);
            }
        }
        public static string Grid_LastName {
            get {
                return ResourceManager.GetString("Grid_LastName", resourceCulture);
            }
        }
        public static string Grid_Email {
            get {
                return ResourceManager.GetString("Grid_Email", resourceCulture);
            }
        }
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        public static string Lbl_UsernameReq {
            get {
                return ResourceManager.GetString("Lbl_UsernameReq", resourceCulture);
            }
        }
        public static string Lbl_PasswordReq {
            get {
                return ResourceManager.GetString("Lbl_PasswordReq", resourceCulture);
            }
        }
        public static string Lbl_Role {
            get {
                return ResourceManager.GetString("Lbl_Role", resourceCulture);
            }
        }
        public static string Lbl_Email {
            get {
                return ResourceManager.GetString("Lbl_Email", resourceCulture);
            }
        }
        public static string Lbl_FirstName {
            get {
                return ResourceManager.GetString("Lbl_FirstName", resourceCulture);
            }
        }
        public static string Lbl_LastName {
            get {
                return ResourceManager.GetString("Lbl_LastName", resourceCulture);
            }
        }
        public static string Btn_AddUser {
            get {
                return ResourceManager.GetString("Btn_AddUser", resourceCulture);
            }
        }
        public static string ToolTip_ChangeConfig {
            get {
                return ResourceManager.GetString("ToolTip_ChangeConfig", resourceCulture);
            }
        }
        public static string ToolTip_ExportConfig {
            get {
                return ResourceManager.GetString("ToolTip_ExportConfig", resourceCulture);
            }
        }
        public static string ToolTip_PortDefault {
            get {
                return ResourceManager.GetString("ToolTip_PortDefault", resourceCulture);
            }
        }
        public static string ToolTip_ServerName {
            get {
                return ResourceManager.GetString("ToolTip_ServerName", resourceCulture);
            }
        }
        public static string ToolTip_SelectFileInFolder {
            get {
                return ResourceManager.GetString("ToolTip_SelectFileInFolder", resourceCulture);
            }
        }
        public static string ToolTip_DashboardJson {
            get {
                return ResourceManager.GetString("ToolTip_DashboardJson", resourceCulture);
            }
        }
        public static string ToolTip_OfflineFolder {
            get {
                return ResourceManager.GetString("ToolTip_OfflineFolder", resourceCulture);
            }
        }
        public static string ToolTip_SelectOfflineFolder {
            get {
                return ResourceManager.GetString("ToolTip_SelectOfflineFolder", resourceCulture);
            }
        }
        public static string ToolTip_RowLimit {
            get {
                return ResourceManager.GetString("ToolTip_RowLimit", resourceCulture);
            }
        }
        public static string Title_ExportConfig {
            get {
                return ResourceManager.GetString("Title_ExportConfig", resourceCulture);
            }
        }
        public static string Msg_ConfigExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ConfigExportSuccess", resourceCulture);
            }
        }
        public static string Title_Export {
            get {
                return ResourceManager.GetString("Title_Export", resourceCulture);
            }
        }
        public static string Title_SelectConfigLocation {
            get {
                return ResourceManager.GetString("Title_SelectConfigLocation", resourceCulture);
            }
        }
        public static string Title_SelectFileInFolder {
            get {
                return ResourceManager.GetString("Title_SelectFileInFolder", resourceCulture);
            }
        }
        public static string Title_SelectOfflineFolder {
            get {
                return ResourceManager.GetString("Title_SelectOfflineFolder", resourceCulture);
            }
        }
        public static string Status_FetchingTables {
            get {
                return ResourceManager.GetString("Status_FetchingTables", resourceCulture);
            }
        }
        public static string Status_ReadyBackup {
            get {
                return ResourceManager.GetString("Status_ReadyBackup", resourceCulture);
            }
        }
        public static string Status_ErrorFetchingTables {
            get {
                return ResourceManager.GetString("Status_ErrorFetchingTables", resourceCulture);
            }
        }
        public static string Msg_OfflineFolderRequired {
            get {
                return ResourceManager.GetString("Msg_OfflineFolderRequired", resourceCulture);
            }
        }
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        public static string Status_DownloadingTable {
            get {
                return ResourceManager.GetString("Status_DownloadingTable", resourceCulture);
            }
        }
        public static string Status_OfflineImageCreated {
            get {
                return ResourceManager.GetString("Status_OfflineImageCreated", resourceCulture);
            }
        }
        public static string Msg_OfflineBackupSuccess {
            get {
                return ResourceManager.GetString("Msg_OfflineBackupSuccess", resourceCulture);
            }
        }
        public static string Title_BackupComplete {
            get {
                return ResourceManager.GetString("Title_BackupComplete", resourceCulture);
            }
        }
        public static string Status_BackupFailed {
            get {
                return ResourceManager.GetString("Status_BackupFailed", resourceCulture);
            }
        }
        public static string Msg_OfflineBackupFailed {
            get {
                return ResourceManager.GetString("Msg_OfflineBackupFailed", resourceCulture);
            }
        }
        public static string Msg_InvalidPort {
            get {
                return ResourceManager.GetString("Msg_InvalidPort", resourceCulture);
            }
        }
        public static string Title_ValidationError {
            get {
                return ResourceManager.GetString("Title_ValidationError", resourceCulture);
            }
        }
        public static string Status_LoadedUsers {
            get {
                return ResourceManager.GetString("Status_LoadedUsers", resourceCulture);
            }
        }
        public static string Status_ErrorLoadingUsers {
            get {
                return ResourceManager.GetString("Status_ErrorLoadingUsers", resourceCulture);
            }
        }
        public static string Msg_UsernamePasswordRequired {
            get {
                return ResourceManager.GetString("Msg_UsernamePasswordRequired", resourceCulture);
            }
        }
        public static string Msg_CannotDeleteAdmin {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteAdmin", resourceCulture);
            }
        }
        public static string Title_Stop {
            get {
                return ResourceManager.GetString("Title_Stop", resourceCulture);
            }
        }
        public static string Msg_ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteUser", resourceCulture);
            }
        }
        public static string Title_Confirm {
            get {
                return ResourceManager.GetString("Title_Confirm", resourceCulture);
            }
        }
        public static string Status_CheckingNetwork {
            get {
                return ResourceManager.GetString("Status_CheckingNetwork", resourceCulture);
            }
        }
        public static string Status_InvalidPort {
            get {
                return ResourceManager.GetString("Status_InvalidPort", resourceCulture);
            }
        }
        public static string Msg_PingFailed {
            get {
                return ResourceManager.GetString("Msg_PingFailed", resourceCulture);
            }
        }
        public static string Title_NetworkError {
            get {
                return ResourceManager.GetString("Title_NetworkError", resourceCulture);
            }
        }
        public static string Status_TestingConnections {
            get {
                return ResourceManager.GetString("Status_TestingConnections", resourceCulture);
            }
        }
        public static string Status_DbMissing {
            get {
                return ResourceManager.GetString("Status_DbMissing", resourceCulture);
            }
        }
        public static string Msg_DbMissingDetail {
            get {
                return ResourceManager.GetString("Msg_DbMissingDetail", resourceCulture);
            }
        }
        public static string Title_Connected {
            get {
                return ResourceManager.GetString("Title_Connected", resourceCulture);
            }
        }
        public static string Msg_ConnectionSuccess {
            get {
                return ResourceManager.GetString("Msg_ConnectionSuccess", resourceCulture);
            }
        }
        public static string Title_Success {
            get {
                return ResourceManager.GetString("Title_Success", resourceCulture);
            }
        }
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        public static string Msg_ConnectionFailedDetail {
            get {
                return ResourceManager.GetString("Msg_ConnectionFailedDetail", resourceCulture);
            }
        }
        public static string Title_Failed {
            get {
                return ResourceManager.GetString("Title_Failed", resourceCulture);
            }
        }
        public static string Msg_InvalidPortDetail {
            get {
                return ResourceManager.GetString("Msg_InvalidPortDetail", resourceCulture);
            }
        }
        public static string Msg_CheckIP {
            get {
                return ResourceManager.GetString("Msg_CheckIP", resourceCulture);
            }
        }
        public static string Msg_CheckFirewall {
            get {
                return ResourceManager.GetString("Msg_CheckFirewall", resourceCulture);
            }
        }
        public static string Msg_CheckHostOn {
            get {
                return ResourceManager.GetString("Msg_CheckHostOn", resourceCulture);
            }
        }
        public static string Msg_DbMissingSaveRestart {
            get {
                return ResourceManager.GetString("Msg_DbMissingSaveRestart", resourceCulture);
            }
        }
        public static string Title_Auth {
            get {
                return ResourceManager.GetString("Title_Auth", resourceCulture);
            }
        }
        public static string Title_Data {
            get {
                return ResourceManager.GetString("Title_Data", resourceCulture);
            }
        }
        public static string Msg_ConnectionFailed {
            get {
                return ResourceManager.GetString("Msg_ConnectionFailed", resourceCulture);
            }
        }
        public static string Filter_JsonFiles {
            get {
                return ResourceManager.GetString("Filter_JsonFiles", resourceCulture);
            }
        }
        public static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        public static string Str_Ref {
            get {
                return ResourceManager.GetString("Str_Ref", resourceCulture);
            }
        }
        public static string Msg_CopySuccess {
            get {
                return ResourceManager.GetString("Msg_CopySuccess", resourceCulture);
            }
        }
        public static string Str_DetailedAnalysis {
            get {
                return ResourceManager.GetString("Str_DetailedAnalysis", resourceCulture);
            }
        }
        public static string Msg_CopyError {
            get {
                return ResourceManager.GetString("Msg_CopyError", resourceCulture);
            }
        }
        public static string Msg_CopyNoData {
            get {
                return ResourceManager.GetString("Msg_CopyNoData", resourceCulture);
            }
        }
        public static string Str_Error {
            get {
                return ResourceManager.GetString("Str_Error", resourceCulture);
            }
        }
        public static string Ana_RangeSlider {
            get {
                return ResourceManager.GetString("Ana_RangeSlider", resourceCulture);
            }
        }
        public static string Str_AddDataColumn {
            get {
                return ResourceManager.GetString("Str_AddDataColumn", resourceCulture);
            }
        }
        public static string Str_AddRule {
            get {
                return ResourceManager.GetString("Str_AddRule", resourceCulture);
            }
        }
        public static string Str_AddValueColumn {
            get {
                return ResourceManager.GetString("Str_AddValueColumn", resourceCulture);
            }
        }
        public static string Str_ApplyClose {
            get {
                return ResourceManager.GetString("Str_ApplyClose", resourceCulture);
            }
        }
        public static string Str_BlankTable {
            get {
                return ResourceManager.GetString("Str_BlankTable", resourceCulture);
            }
        }
        public static string Str_BrowseEllipsis {
            get {
                return ResourceManager.GetString("Str_BrowseEllipsis", resourceCulture);
            }
        }
        public static string Str_Cancel {
            get {
                return ResourceManager.GetString("Str_Cancel", resourceCulture);
            }
        }
        public static string Str_CategoryConfigTitle {
            get {
                return ResourceManager.GetString("Str_CategoryConfigTitle", resourceCulture);
            }
        }
        public static string Str_CategoryMappingRules {
            get {
                return ResourceManager.GetString("Str_CategoryMappingRules", resourceCulture);
            }
        }
        public static string Str_CategoryX {
            get {
                return ResourceManager.GetString("Str_CategoryX", resourceCulture);
            }
        }
        public static string Str_ChartType {
            get {
                return ResourceManager.GetString("Str_ChartType", resourceCulture);
            }
        }
        public static string Str_CollapseFilters {
            get {
                return ResourceManager.GetString("Str_CollapseFilters", resourceCulture);
            }
        }
        public static string Str_CreateNewDBTable {
            get {
                return ResourceManager.GetString("Str_CreateNewDBTable", resourceCulture);
            }
        }
        public static string Str_CreateNewTable {
            get {
                return ResourceManager.GetString("Str_CreateNewTable", resourceCulture);
            }
        }
        public static string Str_CreateTableHint {
            get {
                return ResourceManager.GetString("Str_CreateTableHint", resourceCulture);
            }
        }
        public static string Str_DashboardConfig {
            get {
                return ResourceManager.GetString("Str_DashboardConfig", resourceCulture);
            }
        }
        public static string Str_DataAggregate {
            get {
                return ResourceManager.GetString("Str_DataAggregate", resourceCulture);
            }
        }
        public static string Str_DataStructure {
            get {
                return ResourceManager.GetString("Str_DataStructure", resourceCulture);
            }
        }
        public static string Str_DateColumnFilter {
            get {
                return ResourceManager.GetString("Str_DateColumnFilter", resourceCulture);
            }
        }
        public static string Str_DateRollUp {
            get {
                return ResourceManager.GetString("Str_DateRollUp", resourceCulture);
            }
        }
        public static string Str_DefineRulesHint {
            get {
                return ResourceManager.GetString("Str_DefineRulesHint", resourceCulture);
            }
        }
        public static string Str_DeleteRule {
            get {
                return ResourceManager.GetString("Str_DeleteRule", resourceCulture);
            }
        }
        public static string Str_DetailedEntryHint {
            get {
                return ResourceManager.GetString("Str_DetailedEntryHint", resourceCulture);
            }
        }
        public static string Str_DetailedEntryWizard {
            get {
                return ResourceManager.GetString("Str_DetailedEntryWizard", resourceCulture);
            }
        }
        public static string Str_DetailedRecordEntry {
            get {
                return ResourceManager.GetString("Str_DetailedRecordEntry", resourceCulture);
            }
        }
        public static string Str_DownloadTemplate {
            get {
                return ResourceManager.GetString("Str_DownloadTemplate", resourceCulture);
            }
        }
        public static string Str_EnableChart {
            get {
                return ResourceManager.GetString("Str_EnableChart", resourceCulture);
            }
        }
        public static string Str_ErrorCategories {
            get {
                return ResourceManager.GetString("Str_ErrorCategories", resourceCulture);
            }
        }
        public static string Str_ExcelFile {
            get {
                return ResourceManager.GetString("Str_ExcelFile", resourceCulture);
            }
        }
        public static string Str_ExpandFilters {
            get {
                return ResourceManager.GetString("Str_ExpandFilters", resourceCulture);
            }
        }
        public static string Str_ExportExcel {
            get {
                return ResourceManager.GetString("Str_ExportExcel", resourceCulture);
            }
        }
        public static string Str_FilterMode {
            get {
                return ResourceManager.GetString("Str_FilterMode", resourceCulture);
            }
        }
        public static string Str_FixedLabels {
            get {
                return ResourceManager.GetString("Str_FixedLabels", resourceCulture);
            }
        }
        public static string Str_FormatHint {
            get {
                return ResourceManager.GetString("Str_FormatHint", resourceCulture);
            }
        }
        public static string Str_Fullscreen {
            get {
                return ResourceManager.GetString("Str_Fullscreen", resourceCulture);
            }
        }
        public static string Str_Global {
            get {
                return ResourceManager.GetString("Str_Global", resourceCulture);
            }
        }
        public static string Str_GroupAsCategory {
            get {
                return ResourceManager.GetString("Str_GroupAsCategory", resourceCulture);
            }
        }
        public static string Str_GroupBy {
            get {
                return ResourceManager.GetString("Str_GroupBy", resourceCulture);
            }
        }
        public static string Str_GroupBySlices {
            get {
                return ResourceManager.GetString("Str_GroupBySlices", resourceCulture);
            }
        }
        public static string Str_HideNumbers {
            get {
                return ResourceManager.GetString("Str_HideNumbers", resourceCulture);
            }
        }
        public static string Str_Hierarchy {
            get {
                return ResourceManager.GetString("Str_Hierarchy", resourceCulture);
            }
        }
        public static string Str_HierarchyImport {
            get {
                return ResourceManager.GetString("Str_HierarchyImport", resourceCulture);
            }
        }
        public static string Str_HierarchyImportWizard {
            get {
                return ResourceManager.GetString("Str_HierarchyImportWizard", resourceCulture);
            }
        }
        public static string Str_HoverTooltips {
            get {
                return ResourceManager.GetString("Str_HoverTooltips", resourceCulture);
            }
        }
        public static string Str_Hub {
            get {
                return ResourceManager.GetString("Str_Hub", resourceCulture);
            }
        }
        public static string Str_IgnoreHyphen {
            get {
                return ResourceManager.GetString("Str_IgnoreHyphen", resourceCulture);
            }
        }
        public static string Str_IgnoreLastRows {
            get {
                return ResourceManager.GetString("Str_IgnoreLastRows", resourceCulture);
            }
        }
        public static string Str_IgnoreNoDate {
            get {
                return ResourceManager.GetString("Str_IgnoreNoDate", resourceCulture);
            }
        }
        public static string Str_IgnoreNumbers {
            get {
                return ResourceManager.GetString("Str_IgnoreNumbers", resourceCulture);
            }
        }
        public static string Str_ImportData {
            get {
                return ResourceManager.GetString("Str_ImportData", resourceCulture);
            }
        }
        public static string Str_ImportExcel {
            get {
                return ResourceManager.GetString("Str_ImportExcel", resourceCulture);
            }
        }
        public static string Str_ImportHierarchy {
            get {
                return ResourceManager.GetString("Str_ImportHierarchy", resourceCulture);
            }
        }
        public static string Str_ImportHint {
            get {
                return ResourceManager.GetString("Str_ImportHint", resourceCulture);
            }
        }
        public static string Str_ImportWizard {
            get {
                return ResourceManager.GetString("Str_ImportWizard", resourceCulture);
            }
        }
        public static string Str_IncludeDataExport {
            get {
                return ResourceManager.GetString("Str_IncludeDataExport", resourceCulture);
            }
        }
        public static string Str_InitialDate {
            get {
                return ResourceManager.GetString("Str_InitialDate", resourceCulture);
            }
        }
        public static string Str_LabelAppearance {
            get {
                return ResourceManager.GetString("Str_LabelAppearance", resourceCulture);
            }
        }
        public static string Str_LabelingMode {
            get {
                return ResourceManager.GetString("Str_LabelingMode", resourceCulture);
            }
        }
        public static string Str_LabelSettings {
            get {
                return ResourceManager.GetString("Str_LabelSettings", resourceCulture);
            }
        }
        public static string Str_Machines {
            get {
                return ResourceManager.GetString("Str_Machines", resourceCulture);
            }
        }
        public static string Str_MapColumns {
            get {
                return ResourceManager.GetString("Str_MapColumns", resourceCulture);
            }
        }
        public static string Str_Mix {
            get {
                return ResourceManager.GetString("Str_Mix", resourceCulture);
            }
        }
        public static string Str_MixActive {
            get {
                return ResourceManager.GetString("Str_MixActive", resourceCulture);
            }
        }
        public static string Str_NewRow {
            get {
                return ResourceManager.GetString("Str_NewRow", resourceCulture);
            }
        }
        public static string Str_NewTableName {
            get {
                return ResourceManager.GetString("Str_NewTableName", resourceCulture);
            }
        }
        public static string Str_NumberFormatHint {
            get {
                return ResourceManager.GetString("Str_NumberFormatHint", resourceCulture);
            }
        }
        public static string Str_OfflineMode {
            get {
                return ResourceManager.GetString("Str_OfflineMode", resourceCulture);
            }
        }
        public static string Str_OK {
            get {
                return ResourceManager.GetString("Str_OK", resourceCulture);
            }
        }
        public static string Str_Options {
            get {
                return ResourceManager.GetString("Str_Options", resourceCulture);
            }
        }
        public static string Str_PieChartFixed {
            get {
                return ResourceManager.GetString("Str_PieChartFixed", resourceCulture);
            }
        }
        public static string Str_PortalHubConfig {
            get {
                return ResourceManager.GetString("Str_PortalHubConfig", resourceCulture);
            }
        }
        public static string Str_PortalSettings {
            get {
                return ResourceManager.GetString("Str_PortalSettings", resourceCulture);
            }
        }
        public static string Str_PortalSettingsHint {
            get {
                return ResourceManager.GetString("Str_PortalSettingsHint", resourceCulture);
            }
        }
        public static string Str_PreviewData {
            get {
                return ResourceManager.GetString("Str_PreviewData", resourceCulture);
            }
        }
        public static string Str_PriceTrendLegend {
            get {
                return ResourceManager.GetString("Str_PriceTrendLegend", resourceCulture);
            }
        }
        public static string Str_Priority {
            get {
                return ResourceManager.GetString("Str_Priority", resourceCulture);
            }
        }
        public static string Str_PriorityHint {
            get {
                return ResourceManager.GetString("Str_PriorityHint", resourceCulture);
            }
        }
        public static string Str_Range {
            get {
                return ResourceManager.GetString("Str_Range", resourceCulture);
            }
        }
        public static string Str_Rename {
            get {
                return ResourceManager.GetString("Str_Rename", resourceCulture);
            }
        }
        public static string Str_Reset {
            get {
                return ResourceManager.GetString("Str_Reset", resourceCulture);
            }
        }
        public static string Str_RowsToIgnore {
            get {
                return ResourceManager.GetString("Str_RowsToIgnore", resourceCulture);
            }
        }
        public static string Str_RunAdvancedImport {
            get {
                return ResourceManager.GetString("Str_RunAdvancedImport", resourceCulture);
            }
        }
        public static string Str_SaveClose {
            get {
                return ResourceManager.GetString("Str_SaveClose", resourceCulture);
            }
        }
        public static string Str_SaveRecord {
            get {
                return ResourceManager.GetString("Str_SaveRecord", resourceCulture);
            }
        }
        public static string Str_SearchColumn {
            get {
                return ResourceManager.GetString("Str_SearchColumn", resourceCulture);
            }
        }
        public static string Str_SearchDots {
            get {
                return ResourceManager.GetString("Str_SearchDots", resourceCulture);
            }
        }
        public static string Str_SelectChartPos {
            get {
                return ResourceManager.GetString("Str_SelectChartPos", resourceCulture);
            }
        }
        public static string Str_SelectItemsDisplay {
            get {
                return ResourceManager.GetString("Str_SelectItemsDisplay", resourceCulture);
            }
        }
        public static string Str_SelectSlicesDisplay {
            get {
                return ResourceManager.GetString("Str_SelectSlicesDisplay", resourceCulture);
            }
        }
        public static string Str_SelectSourceFile {
            get {
                return ResourceManager.GetString("Str_SelectSourceFile", resourceCulture);
            }
        }
        public static string Str_ShowAsKpiCards {
            get {
                return ResourceManager.GetString("Str_ShowAsKpiCards", resourceCulture);
            }
        }
        public static string Str_SimplifyLabels {
            get {
                return ResourceManager.GetString("Str_SimplifyLabels", resourceCulture);
            }
        }
        public static string Str_SliderTickStep {
            get {
                return ResourceManager.GetString("Str_SliderTickStep", resourceCulture);
            }
        }
        public static string Str_StandardTimelineTemplate {
            get {
                return ResourceManager.GetString("Str_StandardTimelineTemplate", resourceCulture);
            }
        }
        public static string Str_StartImport {
            get {
                return ResourceManager.GetString("Str_StartImport", resourceCulture);
            }
        }
        public static string Str_StartsWithRaw {
            get {
                return ResourceManager.GetString("Str_StartsWithRaw", resourceCulture);
            }
        }
        public static string Str_StartWithTemplate {
            get {
                return ResourceManager.GetString("Str_StartWithTemplate", resourceCulture);
            }
        }
        public static string Str_SummaryBreakdown {
            get {
                return ResourceManager.GetString("Str_SummaryBreakdown", resourceCulture);
            }
        }
        public static string Str_TableColumns {
            get {
                return ResourceManager.GetString("Str_TableColumns", resourceCulture);
            }
        }
        public static string Str_TableNote {
            get {
                return ResourceManager.GetString("Str_TableNote", resourceCulture);
            }
        }
        public static string Str_TargetTable {
            get {
                return ResourceManager.GetString("Str_TargetTable", resourceCulture);
            }
        }
        public static string Str_To {
            get {
                return ResourceManager.GetString("Str_To", resourceCulture);
            }
        }
        public static string Str_UpdatePreview {
            get {
                return ResourceManager.GetString("Str_UpdatePreview", resourceCulture);
            }
        }
        public static string Str_UseInitialDate {
            get {
                return ResourceManager.GetString("Str_UseInitialDate", resourceCulture);
            }
        }
        public static string Str_ValueAggregation {
            get {
                return ResourceManager.GetString("Str_ValueAggregation", resourceCulture);
            }
        }
        public static string Str_ValueColumnsY {
            get {
                return ResourceManager.GetString("Str_ValueColumnsY", resourceCulture);
            }
        }
        public static string Str_VirtualDate {
            get {
                return ResourceManager.GetString("Str_VirtualDate", resourceCulture);
            }
        }
        public static string Tip_ClearSearch {
            get {
                return ResourceManager.GetString("Tip_ClearSearch", resourceCulture);
            }
        }
        public static string Tip_ConfigCategories {
            get {
                return ResourceManager.GetString("Tip_ConfigCategories", resourceCulture);
            }
        }
        public static string Tip_CopyCategories {
            get {
                return ResourceManager.GetString("Tip_CopyCategories", resourceCulture);
            }
        }
        public static string Tip_DailyTimeline {
            get {
                return ResourceManager.GetString("Tip_DailyTimeline", resourceCulture);
            }
        }
        public static string Tip_DeleteTable {
            get {
                return ResourceManager.GetString("Tip_DeleteTable", resourceCulture);
            }
        }
        public static string Tip_FilterSettings {
            get {
                return ResourceManager.GetString("Tip_FilterSettings", resourceCulture);
            }
        }
        public static string Tip_FindInDataReport {
            get {
                return ResourceManager.GetString("Tip_FindInDataReport", resourceCulture);
            }
        }
        public static string Tip_IgnoreHyphen {
            get {
                return ResourceManager.GetString("Tip_IgnoreHyphen", resourceCulture);
            }
        }
        public static string Tip_IgnoreNumbers {
            get {
                return ResourceManager.GetString("Tip_IgnoreNumbers", resourceCulture);
            }
        }
        public static string Tip_MinToClock {
            get {
                return ResourceManager.GetString("Tip_MinToClock", resourceCulture);
            }
        }
        public static string Tip_NextDay {
            get {
                return ResourceManager.GetString("Tip_NextDay", resourceCulture);
            }
        }
        public static string Tip_NextWeek {
            get {
                return ResourceManager.GetString("Tip_NextWeek", resourceCulture);
            }
        }
        public static string Tip_NodeEditor {
            get {
                return ResourceManager.GetString("Tip_NodeEditor", resourceCulture);
            }
        }
        public static string Tip_PrevDay {
            get {
                return ResourceManager.GetString("Tip_PrevDay", resourceCulture);
            }
        }
        public static string Tip_PrevWeek {
            get {
                return ResourceManager.GetString("Tip_PrevWeek", resourceCulture);
            }
        }
        public static string Tip_PrintReport {
            get {
                return ResourceManager.GetString("Tip_PrintReport", resourceCulture);
            }
        }
        public static string Tip_RefreshRecolor {
            get {
                return ResourceManager.GetString("Tip_RefreshRecolor", resourceCulture);
            }
        }
        public static string Tip_ReturnHub {
            get {
                return ResourceManager.GetString("Tip_ReturnHub", resourceCulture);
            }
        }
        public static string Tip_SetFixedColor {
            get {
                return ResourceManager.GetString("Tip_SetFixedColor", resourceCulture);
            }
        }
        public static string Tip_SwitchAdvanced {
            get {
                return ResourceManager.GetString("Tip_SwitchAdvanced", resourceCulture);
            }
        }
        public static string Tip_SwitchView {
            get {
                return ResourceManager.GetString("Tip_SwitchView", resourceCulture);
            }
        }
        public static string Tip_ToggleFullscreen {
            get {
                return ResourceManager.GetString("Tip_ToggleFullscreen", resourceCulture);
            }
        }
        public static string Title_Saved {
            get {
                return ResourceManager.GetString("Title_Saved", resourceCulture);
            }
        }
        public static string Msg_RulesSaved {
            get {
                return ResourceManager.GetString("Msg_RulesSaved", resourceCulture);
            }
        }
        public static string Str_Unknown {
            get {
                return ResourceManager.GetString("Str_Unknown", resourceCulture);
            }
        }
        public static string Str_ExportRulesDialog {
            get {
                return ResourceManager.GetString("Str_ExportRulesDialog", resourceCulture);
            }
        }
        public static string Msg_ExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ExportSuccess", resourceCulture);
            }
        }
        public static string Msg_ExportFailed {
            get {
                return ResourceManager.GetString("Msg_ExportFailed", resourceCulture);
            }
        }
        public static string Str_ImportRulesDialog {
            get {
                return ResourceManager.GetString("Str_ImportRulesDialog", resourceCulture);
            }
        }
        public static string Msg_ImportedRules {
            get {
                return ResourceManager.GetString("Msg_ImportedRules", resourceCulture);
            }
        }
        public static string Msg_ImportFailed {
            get {
                return ResourceManager.GetString("Msg_ImportFailed", resourceCulture);
            }
        }
    }
}

