//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_LoginForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Entry Line.
        /// </summary>
        public static string AddDataLine {
            get {
                return ResourceManager.GetString("AddDataLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ID Column.
        /// </summary>
        public static string AddId {
            get {
                return ResourceManager.GetString("AddId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Category:.
        /// </summary>
        public static string Ana_Category {
            get {
                return ResourceManager.GetString("Ana_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Ana_EndDate {
            get {
                return ResourceManager.GetString("Ana_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal and Breaks Excluded.
        /// </summary>
        public static string Ana_ExcludeMachine00 {
            get {
                return ResourceManager.GetString("Ana_ExcludeMachine00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data.
        /// </summary>
        public static string Ana_LoadData {
            get {
                return ResourceManager.GetString("Ana_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Ana_StartDate {
            get {
                return ResourceManager.GetString("Ana_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        public static string Ana_Table {
            get {
                return ResourceManager.GetString("Ana_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Analytics Dashboard.
        /// </summary>
        public static string Ana_Title {
            get {
                return ResourceManager.GetString("Ana_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity Breakdown(Duration).
        /// </summary>
        public static string AnalyticsP2_BarTitle {
            get {
                return ResourceManager.GetString("AnalyticsP2_BarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Stop/Day.
        /// </summary>
        public static string AnalyticsP2_Card_1 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Error/Day.
        /// </summary>
        public static string AnalyticsP2_Card_2 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Breaks And Parallel Maintenance.
        /// </summary>
        public static string AnalyticsP2_Card_3 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Working /Day.
        /// </summary>
        public static string AnalyticsP2_Card_4 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Stop/day (Total ; meals And Breaks Included).
        /// </summary>
        public static string AnalyticsP2_Card_5 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine with the Most Frequent Errors.
        /// </summary>
        public static string AnalyticsP2_Card_6 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Saved from a Non-Critical Failure.
        /// </summary>
        public static string AnalyticsP2_Card_7 {
            get {
                return ResourceManager.GetString("AnalyticsP2_Card_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string AnalyticsP2_Error {
            get {
                return ResourceManager.GetString("AnalyticsP2_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors vs Stops.
        /// </summary>
        public static string AnalyticsP2_PieTitle_1 {
            get {
                return ResourceManager.GetString("AnalyticsP2_PieTitle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Ä°mpact.
        /// </summary>
        public static string AnalyticsP2_PieTitle_2 {
            get {
                return ResourceManager.GetString("AnalyticsP2_PieTitle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops.
        /// </summary>
        public static string AnalyticsP2_Stop {
            get {
                return ResourceManager.GetString("AnalyticsP2_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Incident Duration.
        /// </summary>
        public static string Chart_LongestIncident {
            get {
                return ResourceManager.GetString("Chart_LongestIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Breakdown (Total).
        /// </summary>
        public static string Chart_MachineDist {
            get {
                return ResourceManager.GetString("Chart_MachineDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown by Category.
        /// </summary>
        public static string Chart_ShiftDist {
            get {
                return ResourceManager.GetString("Chart_ShiftDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Col_Date {
            get {
                return ResourceManager.GetString("Col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Col_Duration {
            get {
                return ResourceManager.GetString("Col_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Col_Machine {
            get {
                return ResourceManager.GetString("Col_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Col_Shift {
            get {
                return ResourceManager.GetString("Col_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Col_Timeline {
            get {
                return ResourceManager.GetString("Col_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Table....
        /// </summary>
        public static string CreateNewTable {
            get {
                return ResourceManager.GetString("CreateNewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Provider:.
        /// </summary>
        public static string DbProvider {
            get {
                return ResourceManager.GetString("DbProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        public static string Drill_Count {
            get {
                return ResourceManager.GetString("Drill_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Error Analysis.
        /// </summary>
        public static string Drill_Title {
            get {
                return ResourceManager.GetString("Drill_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL DURATION.
        /// </summary>
        public static string Drill_TotalDuration {
            get {
                return ResourceManager.GetString("Drill_TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string DurationText {
            get {
                return ResourceManager.GetString("DurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ID.
        /// </summary>
        public static string EditId {
            get {
                return ResourceManager.GetString("EditId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date:.
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Error Analysis.
        /// </summary>
        public static string Error_Analysis {
            get {
                return ResourceManager.GetString("Error_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Date:.
        /// </summary>
        public static string FilterbyDate {
            get {
                return ResourceManager.GetString("FilterbyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide ID.
        /// </summary>
        public static string HideId {
            get {
                return ResourceManager.GetString("HideId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Full History.
        /// </summary>
        public static string LoadFullHistory {
            get {
                return ResourceManager.GetString("LoadFullHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Selected.
        /// </summary>
        public static string Machine_Selected {
            get {
                return ResourceManager.GetString("Machine_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize button .
        /// </summary>
        public static string Max_but {
            get {
                return ResourceManager.GetString("Max_but", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Representation.
        /// </summary>
        public static string Min2clock {
            get {
                return ResourceManager.GetString("Min2clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Error: Access Denied (Role Verification Failed)..
        /// </summary>
        public static string Msg_AccessDeniedRole {
            get {
                return ResourceManager.GetString("Msg_AccessDeniedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database initialization failed. Check credentials..
        /// </summary>
        public static string Msg_DbInitFailed {
            get {
                return ResourceManager.GetString("Msg_DbInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Invalid username or password.
        /// </summary>
        public static string Msg_InvalidCredentials {
            get {
                return ResourceManager.GetString("Msg_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network unreachable..
        /// </summary>
        public static string Msg_NetworkUnreachable {
            get {
                return ResourceManager.GetString("Msg_NetworkUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved. Please RESTART the app to apply changes..
        /// </summary>
        public static string Msg_SettingsSavedRestart {
            get {
                return ResourceManager.GetString("Msg_SettingsSavedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User added successfully..
        /// </summary>
        public static string Msg_UserAdded {
            get {
                return ResourceManager.GetString("Msg_UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        public static string Msg_UserDeleted {
            get {
                return ResourceManager.GetString("Msg_UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Nav_Customers {
            get {
                return ResourceManager.GetString("Nav_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Nav_Help {
            get {
                return ResourceManager.GetString("Nav_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string Nav_Logs {
            get {
                return ResourceManager.GetString("Nav_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string P_date {
            get {
                return ResourceManager.GetString("P_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors &amp; Stops.
        /// </summary>
        public static string P_Errors_and_Stops {
            get {
                return ResourceManager.GetString("P_Errors_and_Stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal &amp; Breaks.
        /// </summary>
        public static string P_Meal_and_breaks {
            get {
                return ResourceManager.GetString("P_Meal_and_breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping Error.
        /// </summary>
        public static string P_Overlapping {
            get {
                return ResourceManager.GetString("P-Overlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string P_Running {
            get {
                return ResourceManager.GetString("P_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string P_Shift {
            get {
                return ResourceManager.GetString("P_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stop.
        /// </summary>
        public static string P_Total_Stop {
            get {
                return ResourceManager.GetString("P_Total_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        public static string P_Working_Time {
            get {
                return ResourceManager.GetString("P_Working_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search:.
        /// </summary>
        public static string QuickSearch {
            get {
                return ResourceManager.GetString("QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Column.
        /// </summary>
        public static string RenameColumn {
            get {
                return ResourceManager.GetString("RenameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Report Mode.
        /// </summary>
        public static string ReportMode {
            get {
                return ResourceManager.GetString("ReportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All Changes.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Categories.
        /// </summary>
        public static string Str_CategoryConfig {
            get {
                return ResourceManager.GetString("Str_CategoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Str_Find {
            get {
                return ResourceManager.GetString("Str_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        public static string Str_FindWhat {
            get {
                return ResourceManager.GetString("Str_FindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With....
        /// </summary>
        public static string Str_MappingRule {
            get {
                return ResourceManager.GetString("Str_MappingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group As....
        /// </summary>
        public static string Str_MapTo {
            get {
                return ResourceManager.GetString("Str_MapTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string Str_MatchCase {
            get {
                return ResourceManager.GetString("Str_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Str_Replace {
            get {
                return ResourceManager.GetString("Str_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string Str_ReplaceWith {
            get {
                return ResourceManager.GetString("Str_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new database table from Excel.
        /// </summary>
        public static string Tip_CreateNewTable {
            get {
                return ResourceManager.GetString("Tip_CreateNewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck for speed (Last 500 rows). Check to see everything..
        /// </summary>
        public static string Tip_LoadFullHistory {
            get {
                return ResourceManager.GetString("Tip_LoadFullHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename selected column.
        /// </summary>
        public static string Tip_RenameColumn {
            get {
                return ResourceManager.GetString("Tip_RenameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Unit_Minutes {
            get {
                return ResourceManager.GetString("Unit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        public static string Str_CreateNewDBTable { get { return ResourceManager.GetString("Str_CreateNewDBTable", resourceCulture); } }
        public static string Str_CreateTableHint { get { return ResourceManager.GetString("Str_CreateTableHint", resourceCulture); } }
        public static string Str_NewTableName { get { return ResourceManager.GetString("Str_NewTableName", resourceCulture); } }
        public static string Str_StartWithTemplate { get { return ResourceManager.GetString("Str_StartWithTemplate", resourceCulture); } }
        public static string Str_BlankTable { get { return ResourceManager.GetString("Str_BlankTable", resourceCulture); } }
        public static string Str_StandardTimelineTemplate { get { return ResourceManager.GetString("Str_StandardTimelineTemplate", resourceCulture); } }
        public static string Str_TableColumns { get { return ResourceManager.GetString("Str_TableColumns", resourceCulture); } }
        public static string Str_TableNote { get { return ResourceManager.GetString("Str_TableNote", resourceCulture); } }
        public static string Str_CreateTable { get { return ResourceManager.GetString("Str_CreateTable", resourceCulture); } }
        public static string Str_ImportData { get { return ResourceManager.GetString("Str_ImportData", resourceCulture); } }
        public static string Str_ImportWizard { get { return ResourceManager.GetString("Str_ImportWizard", resourceCulture); } }
        public static string Str_ImportHint { get { return ResourceManager.GetString("Str_ImportHint", resourceCulture); } }
        public static string Str_SelectSourceFile { get { return ResourceManager.GetString("Str_SelectSourceFile", resourceCulture); } }
        public static string Str_BrowseEllipsis { get { return ResourceManager.GetString("Str_BrowseEllipsis", resourceCulture); } }
        public static string Str_ColumnMapping { get { return ResourceManager.GetString("Str_ColumnMapping", resourceCulture); } }
        public static string Str_MappingHint { get { return ResourceManager.GetString("Str_MappingHint", resourceCulture); } }
        public static string Str_StartImport { get { return ResourceManager.GetString("Str_StartImport", resourceCulture); } }
        public static string Str_RowsToIgnore { get { return ResourceManager.GetString("Str_RowsToIgnore", resourceCulture); } }
        public static string Str_HierarchyImport { get { return ResourceManager.GetString("Str_HierarchyImport", resourceCulture); } }
        public static string Str_HierarchyImportWizard { get { return ResourceManager.GetString("Str_HierarchyImportWizard", resourceCulture); } }
        public static string Str_DownloadTemplate { get { return ResourceManager.GetString("Str_DownloadTemplate", resourceCulture); } }
        public static string Str_TargetTable { get { return ResourceManager.GetString("Str_TargetTable", resourceCulture); } }
        public static string Str_ExcelFile { get { return ResourceManager.GetString("Str_ExcelFile", resourceCulture); } }
        public static string Str_MapColumns { get { return ResourceManager.GetString("Str_MapColumns", resourceCulture); } }
        public static string Str_PreviewData { get { return ResourceManager.GetString("Str_PreviewData", resourceCulture); } }
        public static string Str_UpdatePreview { get { return ResourceManager.GetString("Str_UpdatePreview", resourceCulture); } }
        public static string Str_HierarchyImportHint { get { return ResourceManager.GetString("Str_HierarchyImportHint", resourceCulture); } }
        public static string Str_ExcelSourceFile { get { return ResourceManager.GetString("Str_ExcelSourceFile", resourceCulture); } }
        public static string Str_SelectExcelSheet { get { return ResourceManager.GetString("Str_SelectExcelSheet", resourceCulture); } }
        public static string Str_DefineHierarchyLevels { get { return ResourceManager.GetString("Str_DefineHierarchyLevels", resourceCulture); } }
        public static string Str_ImportHierarchy { get { return ResourceManager.GetString("Str_ImportHierarchy", resourceCulture); } }
        public static string Str_PortalSettings { get { return ResourceManager.GetString("Str_PortalSettings", resourceCulture); } }
        public static string Str_PortalHubConfig { get { return ResourceManager.GetString("Str_PortalHubConfig", resourceCulture); } }
        public static string Str_PortalSettingsHint { get { return ResourceManager.GetString("Str_PortalSettingsHint", resourceCulture); } }
        public static string Str_HubConnection { get { return ResourceManager.GetString("Str_HubConnection", resourceCulture); } }
        public static string Str_HubServerURL { get { return ResourceManager.GetString("Str_HubServerURL", resourceCulture); } }
        public static string Str_EnableRealTimeUpdates { get { return ResourceManager.GetString("Str_EnableRealTimeUpdates", resourceCulture); } }
        public static string Str_LocalAnalytics { get { return ResourceManager.GetString("Str_LocalAnalytics", resourceCulture); } }
        public static string Str_AutoRefreshDashboard { get { return ResourceManager.GetString("Str_AutoRefreshDashboard", resourceCulture); } }
        public static string Str_RefreshInterval { get { return ResourceManager.GetString("Str_RefreshInterval", resourceCulture); } }
        public static string Str_SaveSettings { get { return ResourceManager.GetString("Str_SaveSettings", resourceCulture); } }
        public static string Str_DetailedRecordEntry { get { return ResourceManager.GetString("Str_DetailedRecordEntry", resourceCulture); } }
        public static string Str_DetailedEntryWizard { get { return ResourceManager.GetString("Str_DetailedEntryWizard", resourceCulture); } }
        public static string Str_DetailedEntryHint { get { return ResourceManager.GetString("Str_DetailedEntryHint", resourceCulture); } }
        public static string Str_PrimaryInformation { get { return ResourceManager.GetString("Str_PrimaryInformation", resourceCulture); } }
        public static string Str_StartTime { get { return ResourceManager.GetString("Str_StartTime", resourceCulture); } }
        public static string Str_EndTime { get { return ResourceManager.GetString("Str_EndTime", resourceCulture); } }
        public static string Str_MachineCode { get { return ResourceManager.GetString("Str_MachineCode", resourceCulture); } }
        public static string Str_Description { get { return ResourceManager.GetString("Str_Description", resourceCulture); } }
        public static string Str_Categorization { get { return ResourceManager.GetString("Str_Categorization", resourceCulture); } }
        public static string Str_Category { get { return ResourceManager.GetString("Str_Category", resourceCulture); } }
        public static string Str_SaveRecord { get { return ResourceManager.GetString("Str_SaveRecord", resourceCulture); } }
        public static string Str_Cancel { get { return ResourceManager.GetString("Str_Cancel", resourceCulture); } }
        public static string Str_OK { get { return ResourceManager.GetString("Str_OK", resourceCulture); } }
        public static string Str_DetailedAnalysis { get { return ResourceManager.GetString("Str_DetailedAnalysis", resourceCulture); } }
        public static string Str_Global { get { return ResourceManager.GetString("Str_Global", resourceCulture); } }
        public static string Str_Hierarchy { get { return ResourceManager.GetString("Str_Hierarchy", resourceCulture); } }
        public static string Str_SearchColumn { get { return ResourceManager.GetString("Str_SearchColumn", resourceCulture); } }
        public static string Str_HourlyTimeCorrection { get { return ResourceManager.GetString("Str_HourlyTimeCorrection", resourceCulture); } }
        public static string Str_Rename { get { return ResourceManager.GetString("Str_Rename", resourceCulture); } }
        public static string Str_AdvancedImport { get { return ResourceManager.GetString("Str_AdvancedImport", resourceCulture); } }
        public static string Str_RunAdvancedImport { get { return ResourceManager.GetString("Str_RunAdvancedImport", resourceCulture); } }
        public static string Str_To { get { return ResourceManager.GetString("Str_To", resourceCulture); } }
        public static string Str_Reset { get { return ResourceManager.GetString("Str_Reset", resourceCulture); } }
        public static string Str_Options { get { return ResourceManager.GetString("Str_Options", resourceCulture); } }
        public static string Str_NewRow { get { return ResourceManager.GetString("Str_NewRow", resourceCulture); } }
        public static string Str_Fullscreen { get { return ResourceManager.GetString("Str_Fullscreen", resourceCulture); } }
        public static string Str_Hub { get { return ResourceManager.GetString("Str_Hub", resourceCulture); } }
        public static string Str_LabelSettings { get { return ResourceManager.GetString("Str_LabelSettings", resourceCulture); } }
        public static string Str_IgnoreHyphen { get { return ResourceManager.GetString("Str_IgnoreHyphen", resourceCulture); } }
        public static string Str_IgnoreNumbers { get { return ResourceManager.GetString("Str_IgnoreNumbers", resourceCulture); } }
        public static string Str_FilterMode { get { return ResourceManager.GetString("Str_FilterMode", resourceCulture); } }
        public static string Str_IgnoreNoDate { get { return ResourceManager.GetString("Str_IgnoreNoDate", resourceCulture); } }
        public static string Str_VirtualDate { get { return ResourceManager.GetString("Str_VirtualDate", resourceCulture); } }
        public static string Str_UseInitialDate { get { return ResourceManager.GetString("Str_UseInitialDate", resourceCulture); } }
        public static string Str_InitialDate { get { return ResourceManager.GetString("Str_InitialDate", resourceCulture); } }
        public static string Str_SliderTickStep { get { return ResourceManager.GetString("Str_SliderTickStep", resourceCulture); } }
        public static string Str_Range { get { return ResourceManager.GetString("Str_Range", resourceCulture); } }
        public static string Str_IncludeDataExport { get { return ResourceManager.GetString("Str_IncludeDataExport", resourceCulture); } }
        public static string Str_SummaryBreakdown { get { return ResourceManager.GetString("Str_SummaryBreakdown", resourceCulture); } }
        public static string Str_DashboardConfig { get { return ResourceManager.GetString("Str_DashboardConfig", resourceCulture); } }
        public static string Str_SelectChartPos { get { return ResourceManager.GetString("Str_SelectChartPos", resourceCulture); } }
        public static string Str_EnableChart { get { return ResourceManager.GetString("Str_EnableChart", resourceCulture); } }
        public static string Str_DataStructure { get { return ResourceManager.GetString("Str_DataStructure", resourceCulture); } }
        public static string Str_IgnoreLastRows { get { return ResourceManager.GetString("Str_IgnoreLastRows", resourceCulture); } }
        public static string Str_NumberFormatHint { get { return ResourceManager.GetString("Str_NumberFormatHint", resourceCulture); } }
        public static string Str_ChartType { get { return ResourceManager.GetString("Str_ChartType", resourceCulture); } }
        public static string Str_PieChartFixed { get { return ResourceManager.GetString("Str_PieChartFixed", resourceCulture); } }
        public static string Str_ShowAsKpiCards { get { return ResourceManager.GetString("Str_ShowAsKpiCards", resourceCulture); } }
        public static string Str_CategoryX { get { return ResourceManager.GetString("Str_CategoryX", resourceCulture); } }
        public static string Str_GroupBy { get { return ResourceManager.GetString("Str_GroupBy", resourceCulture); } }
        public static string Str_SelectItemsDisplay { get { return ResourceManager.GetString("Str_SelectItemsDisplay", resourceCulture); } }
        public static string Str_LabelingMode { get { return ResourceManager.GetString("Str_LabelingMode", resourceCulture); } }
        public static string Str_HoverTooltips { get { return ResourceManager.GetString("Str_HoverTooltips", resourceCulture); } }
        public static string Str_FixedLabels { get { return ResourceManager.GetString("Str_FixedLabels", resourceCulture); } }
        public static string Str_ValueColumnsY { get { return ResourceManager.GetString("Str_ValueColumnsY", resourceCulture); } }
        public static string Str_PriceTrendLegend { get { return ResourceManager.GetString("Str_PriceTrendLegend", resourceCulture); } }
        public static string Str_Mix { get { return ResourceManager.GetString("Str_Mix", resourceCulture); } }
        public static string Str_MixActive { get { return ResourceManager.GetString("Str_MixActive", resourceCulture); } }
        public static string Str_AddValueColumn { get { return ResourceManager.GetString("Str_AddValueColumn", resourceCulture); } }
        public static string Str_ValueAggregation { get { return ResourceManager.GetString("Str_ValueAggregation", resourceCulture); } }
        public static string Str_DateRollUp { get { return ResourceManager.GetString("Str_DateRollUp", resourceCulture); } }
        public static string Str_DateColumnFilter { get { return ResourceManager.GetString("Str_DateColumnFilter", resourceCulture); } }
        public static string Str_GroupBySlices { get { return ResourceManager.GetString("Str_GroupBySlices", resourceCulture); } }
        public static string Str_SelectSlicesDisplay { get { return ResourceManager.GetString("Str_SelectSlicesDisplay", resourceCulture); } }
        public static string Str_LabelAppearance { get { return ResourceManager.GetString("Str_LabelAppearance", resourceCulture); } }
        public static string Str_HideNumbers { get { return ResourceManager.GetString("Str_HideNumbers", resourceCulture); } }
        public static string Str_SimplifyLabels { get { return ResourceManager.GetString("Str_SimplifyLabels", resourceCulture); } }
        public static string Str_DataAggregate { get { return ResourceManager.GetString("Str_DataAggregate", resourceCulture); } }
        public static string Str_AddDataColumn { get { return ResourceManager.GetString("Str_AddDataColumn", resourceCulture); } }
        public static string Str_ApplyClose { get { return ResourceManager.GetString("Str_ApplyClose", resourceCulture); } }
        public static string Str_Analytics { get { return ResourceManager.GetString("Str_Analytics", resourceCulture); } }
        public static string Str_OfflineMode { get { return ResourceManager.GetString("Str_OfflineMode", resourceCulture); } }
        public static string Msg_CopySuccess { get { return ResourceManager.GetString("Msg_CopySuccess", resourceCulture); } }
        public static string Msg_CopyNoData { get { return ResourceManager.GetString("Msg_CopyNoData", resourceCulture); } }
        public static string Msg_CopyError { get { return ResourceManager.GetString("Msg_CopyError", resourceCulture); } }
        public static string Str_Error { get { return ResourceManager.GetString("Str_Error", resourceCulture); } }
        public static string Str_PrintTimelineReport { get { return ResourceManager.GetString("Str_PrintTimelineReport", resourceCulture); } }
        public static string Str_ReportConfig { get { return ResourceManager.GetString("Str_ReportConfig", resourceCulture); } }
        public static string Str_PrimaryDBTable { get { return ResourceManager.GetString("Str_PrimaryDBTable", resourceCulture); } }
        public static string Str_DateRangeHint { get { return ResourceManager.GetString("Str_DateRangeHint", resourceCulture); } }
        public static string Str_VisualGlobalColors { get { return ResourceManager.GetString("Str_VisualGlobalColors", resourceCulture); } }
        public static string Str_RunningColon { get { return ResourceManager.GetString("Str_RunningColon", resourceCulture); } }
        public static string Str_ErrorsPrimary { get { return ResourceManager.GetString("Str_ErrorsPrimary", resourceCulture); } }
        public static string Str_ErrorsOverlap { get { return ResourceManager.GetString("Str_ErrorsOverlap", resourceCulture); } }
        public static string Str_BypassRunning { get { return ResourceManager.GetString("Str_BypassRunning", resourceCulture); } }
        public static string Str_FacilityStopped { get { return ResourceManager.GetString("Str_FacilityStopped", resourceCulture); } }
        public static string Str_TextInsideEvents { get { return ResourceManager.GetString("Str_TextInsideEvents", resourceCulture); } }
        public static string Str_DefaultTextSize { get { return ResourceManager.GetString("Str_DefaultTextSize", resourceCulture); } }
        public static string Str_MA00Categories { get { return ResourceManager.GetString("Str_MA00Categories", resourceCulture); } }
        public static string Str_GenelTemizlikColon { get { return ResourceManager.GetString("Str_GenelTemizlikColon", resourceCulture); } }
        public static string Str_CayMolasiColon { get { return ResourceManager.GetString("Str_CayMolasiColon", resourceCulture); } }
        public static string Str_YemekMolasiColon { get { return ResourceManager.GetString("Str_YemekMolasiColon", resourceCulture); } }
        public static string Str_DigerMA00Colon { get { return ResourceManager.GetString("Str_DigerMA00Colon", resourceCulture); } }
        public static string Str_DefaultLayersRules { get { return ResourceManager.GetString("Str_DefaultLayersRules", resourceCulture); } }
        public static string Str_LayersHint { get { return ResourceManager.GetString("Str_LayersHint", resourceCulture); } }
        public static string Str_RunningLayer { get { return ResourceManager.GetString("Str_RunningLayer", resourceCulture); } }
        public static string Str_BypassLayer { get { return ResourceManager.GetString("Str_BypassLayer", resourceCulture); } }
        public static string Str_BreaksLayer { get { return ResourceManager.GetString("Str_BreaksLayer", resourceCulture); } }
        public static string Str_ErrorsLayer { get { return ResourceManager.GetString("Str_ErrorsLayer", resourceCulture); } }
        public static string Str_DynamicHeightRules { get { return ResourceManager.GetString("Str_DynamicHeightRules", resourceCulture); } }
        public static string Str_OverlapCascade { get { return ResourceManager.GetString("Str_OverlapCascade", resourceCulture); } }
        public static string Tip_OverlapCascade { get { return ResourceManager.GetString("Tip_OverlapCascade", resourceCulture); } }
        public static string Str_MinMinLabel { get { return ResourceManager.GetString("Str_MinMinLabel", resourceCulture); } }
        public static string Str_MinMinFootnote { get { return ResourceManager.GetString("Str_MinMinFootnote", resourceCulture); } }
        public static string Str_AdvancedLayoutExcel { get { return ResourceManager.GetString("Str_AdvancedLayoutExcel", resourceCulture); } }
        public static string Str_ExcelOverrides { get { return ResourceManager.GetString("Str_ExcelOverrides", resourceCulture); } }
        public static string Str_TimelineRowHeight { get { return ResourceManager.GetString("Str_TimelineRowHeight", resourceCulture); } }
        public static string Str_BlockVisualStyles { get { return ResourceManager.GetString("Str_BlockVisualStyles", resourceCulture); } }
        public static string Str_RoundedCorners { get { return ResourceManager.GetString("Str_RoundedCorners", resourceCulture); } }
        public static string Str_SharpEdges { get { return ResourceManager.GetString("Str_SharpEdges", resourceCulture); } }
        public static string Str_ShowOutlines { get { return ResourceManager.GetString("Str_ShowOutlines", resourceCulture); } }
        public static string Str_ValuesInHours { get { return ResourceManager.GetString("Str_ValuesInHours", resourceCulture); } }
        public static string Str_ShowLabelsOnErrors { get { return ResourceManager.GetString("Str_ShowLabelsOnErrors", resourceCulture); } }
        public static string Str_HideGenelTemizlik { get { return ResourceManager.GetString("Str_HideGenelTemizlik", resourceCulture); } }
        public static string Str_ShowMachineLegend { get { return ResourceManager.GetString("Str_ShowMachineLegend", resourceCulture); } }
        public static string Str_ShowMonthSummary { get { return ResourceManager.GetString("Str_ShowMonthSummary", resourceCulture); } }
        public static string Str_BackToConfig { get { return ResourceManager.GetString("Str_BackToConfig", resourceCulture); } }
        public static string Str_LiveVisualEditor { get { return ResourceManager.GetString("Str_LiveVisualEditor", resourceCulture); } }
        public static string Str_LiveEditorHint { get { return ResourceManager.GetString("Str_LiveEditorHint", resourceCulture); } }
        public static string Str_BlockTimeInfo { get { return ResourceManager.GetString("Str_BlockTimeInfo", resourceCulture); } }
        public static string Str_ForcedCategory { get { return ResourceManager.GetString("Str_ForcedCategory", resourceCulture); } }
        public static string Str_DailyTimeline { get { return ResourceManager.GetString("Str_DailyTimeline", resourceCulture); } }
        public static string Tip_SelectDate { get { return ResourceManager.GetString("Tip_SelectDate", resourceCulture); } }
        public static string Tip_UndoChanges { get { return ResourceManager.GetString("Tip_UndoChanges", resourceCulture); } }
        public static string Tip_RefreshDB { get { return ResourceManager.GetString("Tip_RefreshDB", resourceCulture); } }
        public static string Str_SaveWithIcon { get { return ResourceManager.GetString("Str_SaveWithIcon", resourceCulture); } }
        public static string Str_FavsWithIcon { get { return ResourceManager.GetString("Str_FavsWithIcon", resourceCulture); } }
        public static string Str_AddNewWithIcon { get { return ResourceManager.GetString("Str_AddNewWithIcon", resourceCulture); } }
        public static string Tip_ReturnHub { get { return ResourceManager.GetString("Tip_ReturnHub", resourceCulture); } }
        public static string Tip_RefreshRecolor { get { return ResourceManager.GetString("Tip_RefreshRecolor", resourceCulture); } }
        public static string Tip_NodeEditor { get { return ResourceManager.GetString("Tip_NodeEditor", resourceCulture); } }
        public static string Tip_SetFixedColor { get { return ResourceManager.GetString("Tip_SetFixedColor", resourceCulture); } }
        public static string Tip_ApplyOverrides { get { return ResourceManager.GetString("Tip_ApplyOverrides", resourceCulture); } }
        public static string Tip_CancelRevert { get { return ResourceManager.GetString("Tip_CancelRevert", resourceCulture); } }
        public static string Tip_ResetManualEdits { get { return ResourceManager.GetString("Tip_ResetManualEdits", resourceCulture); } }
        public static string Tip_GeneratePreview { get { return ResourceManager.GetString("Tip_GeneratePreview", resourceCulture); } }
        public static string Tip_PrintA4 { get { return ResourceManager.GetString("Tip_PrintA4", resourceCulture); } }
        public static string Tip_Search { get { return ResourceManager.GetString("Tip_Search", resourceCulture); } }
        public static string Tip_FindInDataReport { get { return ResourceManager.GetString("Tip_FindInDataReport", resourceCulture); } }
        public static string Tip_ToggleFullscreen { get { return ResourceManager.GetString("Tip_ToggleFullscreen", resourceCulture); } }
        public static string Str_BlockFillColor { get { return ResourceManager.GetString("Str_BlockFillColor", resourceCulture); } }
        public static string Str_TextLabelConfig { get { return ResourceManager.GetString("Str_TextLabelConfig", resourceCulture); } }
        public static string Str_InnerBlockText { get { return ResourceManager.GetString("Str_InnerBlockText", resourceCulture); } }
        public static string Str_FontSizeOverride { get { return ResourceManager.GetString("Str_FontSizeOverride", resourceCulture); } }
        public static string Str_XOffset { get { return ResourceManager.GetString("Str_XOffset", resourceCulture); } }
        public static string Str_YOffset { get { return ResourceManager.GetString("Str_YOffset", resourceCulture); } }
        public static string Str_AdvancedLayoutLayering { get { return ResourceManager.GetString("Str_AdvancedLayoutLayering", resourceCulture); } }
        public static string Str_LayerZIndex { get { return ResourceManager.GetString("Str_LayerZIndex", resourceCulture); } }
        public static string Str_HeightScale { get { return ResourceManager.GetString("Str_HeightScale", resourceCulture); } }
        public static string Str_PushDownOffset { get { return ResourceManager.GetString("Str_PushDownOffset", resourceCulture); } }
        public static string Str_ForceFootnotes { get { return ResourceManager.GetString("Str_ForceFootnotes", resourceCulture); } }
        public static string Str_FootnoteDesc { get { return ResourceManager.GetString("Str_FootnoteDesc", resourceCulture); } }
        public static string Str_ApplyOverrides { get { return ResourceManager.GetString("Str_ApplyOverrides", resourceCulture); } }
        public static string Str_CancelRevert { get { return ResourceManager.GetString("Str_CancelRevert", resourceCulture); } }
        public static string Str_ResetManualEdits { get { return ResourceManager.GetString("Str_ResetManualEdits", resourceCulture); } }
        public static string Str_GeneratePreview { get { return ResourceManager.GetString("Str_GeneratePreview", resourceCulture); } }
        public static string Str_PrintA4 { get { return ResourceManager.GetString("Str_PrintA4", resourceCulture); } }
        public static string Tip_PrintReport { get { return ResourceManager.GetString("Tip_PrintReport", resourceCulture); } }
        public static string Tip_FilterSettings { get { return ResourceManager.GetString("Tip_FilterSettings", resourceCulture); } }
        public static string Tip_SwitchView { get { return ResourceManager.GetString("Tip_SwitchView", resourceCulture); } }
        public static string Tip_DailyTimeline { get { return ResourceManager.GetString("Tip_DailyTimeline", resourceCulture); } }
        public static string Tip_SwitchAdvanced { get { return ResourceManager.GetString("Tip_SwitchAdvanced", resourceCulture); } }
        public static string Str_CreateNewTable { get { return ResourceManager.GetString("Str_CreateNewTable", resourceCulture); } }
        public static string Str_CategoryConfigTitle { get { return ResourceManager.GetString("Str_CategoryConfigTitle", resourceCulture); } }
        public static string Str_Edit { get { return ResourceManager.GetString("Str_Edit", resourceCulture); } }
        public static string Tip_DeleteTable { get { return ResourceManager.GetString("Tip_DeleteTable", resourceCulture); } }
        public static string Str_SearchDots { get { return ResourceManager.GetString("Str_SearchDots", resourceCulture); } }
        public static string Tip_CopyCategories { get { return ResourceManager.GetString("Tip_CopyCategories", resourceCulture); } }
        public static string Tip_IgnoreHyphen { get { return ResourceManager.GetString("Tip_IgnoreHyphen", resourceCulture); } }
        public static string Tip_IgnoreNumbers { get { return ResourceManager.GetString("Tip_IgnoreNumbers", resourceCulture); } }
        public static string Str_CategoryMappingRules { get { return ResourceManager.GetString("Str_CategoryMappingRules", resourceCulture); } }
        public static string Str_MolaBakimKazanimi { get { return ResourceManager.GetString("Str_MolaBakimKazanimi", resourceCulture); } }
        public static string Tip_ClearSearch { get { return ResourceManager.GetString("Tip_ClearSearch", resourceCulture); } }
        public static string Str_Machines { get { return ResourceManager.GetString("Str_Machines", resourceCulture); } }
        public static string Tip_ConfigCategories { get { return ResourceManager.GetString("Tip_ConfigCategories", resourceCulture); } }
        public static string Str_DefineRulesHint { get { return ResourceManager.GetString("Str_DefineRulesHint", resourceCulture); } }
        public static string Str_BypassKazanimi { get { return ResourceManager.GetString("Str_BypassKazanimi", resourceCulture); } }
        public static string Tip_HourlyTimeCorrection { get { return ResourceManager.GetString("Tip_HourlyTimeCorrection", resourceCulture); } }
        public static string Str_ErrorCategories { get { return ResourceManager.GetString("Str_ErrorCategories", resourceCulture); } }
        public static string Tip_MinToClock { get { return ResourceManager.GetString("Tip_MinToClock", resourceCulture); } }
        public static string Str_FormatHint { get { return ResourceManager.GetString("Str_FormatHint", resourceCulture); } }
        public static string Str_FiiliSure { get { return ResourceManager.GetString("Str_FiiliSure", resourceCulture); } }
        public static string Str_ExpandFilters { get { return ResourceManager.GetString("Str_ExpandFilters", resourceCulture); } }
        public static string Tip_PrevWeek { get { return ResourceManager.GetString("Tip_PrevWeek", resourceCulture); } }
        public static string Tip_NextWeek { get { return ResourceManager.GetString("Tip_NextWeek", resourceCulture); } }
        public static string Tip_PrevDay { get { return ResourceManager.GetString("Tip_PrevDay", resourceCulture); } }
        public static string Tip_NextDay { get { return ResourceManager.GetString("Tip_NextDay", resourceCulture); } }
        public static string Str_PriorityHint { get { return ResourceManager.GetString("Str_PriorityHint", resourceCulture); } }
        public static string Str_YanlisZamanVerisi { get { return ResourceManager.GetString("Str_YanlisZamanVerisi", resourceCulture); } }
        public static string Str_CollapseFilters { get { return ResourceManager.GetString("Str_CollapseFilters", resourceCulture); } }
        public static string Ana_RangeSlider { get { return ResourceManager.GetString("Ana_RangeSlider", resourceCulture); } }
        public static string Str_Items { get { return ResourceManager.GetString("Str_Items", resourceCulture); } }
        public static string Str_BozukVeri { get { return ResourceManager.GetString("Str_BozukVeri", resourceCulture); } }
        public static string Str_RefData { get { return ResourceManager.GetString("Str_RefData", resourceCulture); } }
        public static string Str_Zoom { get { return ResourceManager.GetString("Str_Zoom", resourceCulture); } }
        public static string Str_DayShift { get { return ResourceManager.GetString("Str_DayShift", resourceCulture); } }
        public static string Str_NightShift { get { return ResourceManager.GetString("Str_NightShift", resourceCulture); } }
        public static string Str_StartsWithRaw { get { return ResourceManager.GetString("Str_StartsWithRaw", resourceCulture); } }
        public static string Str_FavsHint { get { return ResourceManager.GetString("Str_FavsHint", resourceCulture); } }
        public static string Str_GroupAsCategory { get { return ResourceManager.GetString("Str_GroupAsCategory", resourceCulture); } }
        public static string Tip_RemoveFavorite { get { return ResourceManager.GetString("Tip_RemoveFavorite", resourceCulture); } }
        public static string Str_Priority { get { return ResourceManager.GetString("Str_Priority", resourceCulture); } }
        public static string Str_Ref { get { return ResourceManager.GetString("Str_Ref", resourceCulture); } }
        public static string Str_AddRule { get { return ResourceManager.GetString("Str_AddRule", resourceCulture); } }
        public static string Str_EventDetails { get { return ResourceManager.GetString("Str_EventDetails", resourceCulture); } }
        public static string Str_DeleteRule { get { return ResourceManager.GetString("Str_DeleteRule", resourceCulture); } }
        public static string Str_SpecifyEndTime { get { return ResourceManager.GetString("Str_SpecifyEndTime", resourceCulture); } }
        public static string Str_ImportExcel { get { return ResourceManager.GetString("Str_ImportExcel", resourceCulture); } }
        public static string Str_DurationMin { get { return ResourceManager.GetString("Str_DurationMin", resourceCulture); } }
        public static string Str_ExportExcel { get { return ResourceManager.GetString("Str_ExportExcel", resourceCulture); } }
        public static string Tip_ConfigMachineCodes { get { return ResourceManager.GetString("Tip_ConfigMachineCodes", resourceCulture); } }
        public static string Str_FlagAsBypass { get { return ResourceManager.GetString("Str_FlagAsBypass", resourceCulture); } }
        public static string Str_SaveAsFavorite { get { return ResourceManager.GetString("Str_SaveAsFavorite", resourceCulture); } }
        public static string Str_SaveClose { get { return ResourceManager.GetString("Str_SaveClose", resourceCulture); } }
        public static string Str_ApplyToTimeline { get { return ResourceManager.GetString("Str_ApplyToTimeline", resourceCulture); } }
        public static string Str_MA00_1 { get { return ResourceManager.GetString("Str_MA00_1", resourceCulture); } }
        public static string Str_OverlapCascadeStep { get { return ResourceManager.GetString("Str_OverlapCascadeStep", resourceCulture); } }
        public static string Str_AdvancedLayoutToggles { get { return ResourceManager.GetString("Str_AdvancedLayoutToggles", resourceCulture); } }
        public static string Str_MA00_2 { get { return ResourceManager.GetString("Str_MA00_2", resourceCulture); } }
        public static string Str_FootnoteDescription { get { return ResourceManager.GetString("Str_FootnoteDescription", resourceCulture); } }
        public static string Str_MA00_4 { get { return ResourceManager.GetString("Str_MA00_4", resourceCulture); } }
        public static string Str_OverlapErrorColon { get { return ResourceManager.GetString("Str_OverlapErrorColon", resourceCulture); } }
        public static string Str_EditWarning { get { return ResourceManager.GetString("Str_EditWarning", resourceCulture); } }
        public static string Str_MinMinutesLabel { get { return ResourceManager.GetString("Str_MinMinutesLabel", resourceCulture); } }
        public static string Str_FacilityStoppedColon { get { return ResourceManager.GetString("Str_FacilityStoppedColon", resourceCulture); } }
        public static string Str_MA00_3 { get { return ResourceManager.GetString("Str_MA00_3", resourceCulture); } }
        public static string Str_LayerExplanation { get { return ResourceManager.GetString("Str_LayerExplanation", resourceCulture); } }
        public static string Tip_ResetOverrides { get { return ResourceManager.GetString("Tip_ResetOverrides", resourceCulture); } }
        public static string Str_MinMinutesFootnote { get { return ResourceManager.GetString("Str_MinMinutesFootnote", resourceCulture); } }
        public static string Str_ForceIntoFootnotes { get { return ResourceManager.GetString("Str_ForceIntoFootnotes", resourceCulture); } }
        public static string Str_ShowMajorErrorLabels { get { return ResourceManager.GetString("Str_ShowMajorErrorLabels", resourceCulture); } }
        public static string Str_BypassColon { get { return ResourceManager.GetString("Str_BypassColon", resourceCulture); } }
        public static string Str_PrimaryErrorColon { get { return ResourceManager.GetString("Str_PrimaryErrorColon", resourceCulture); } }
    }
}